// Generated from the Government of India Local Government Directory (Ministry of
// Panchayati Raj), via the public CSV mirror at ramSeraph/opendata (blocks.10Jul2026.csv.7z,
// https://github.com/ramSeraph/opendata/releases/tag/lgd-latest-extra1), filtered to
// State Name = "Uttar Pradesh". Mandal groupings are carried over from src/lib/public/
// dummyData.ts (already flagged there as "based on general knowledge, not a verified live
// source"). Block Hindi names are NOT translated (nameHi falls back to the English name) -
// see PR description for why.

export type MandalSeed = { code: string; nameEn: string; nameHi: string };
export type DistrictSeed = { code: string; nameEn: string; nameHi: string; mandalCode: string };
export type BlockSeedRow = { code: string; nameEn: string; nameHi: string; districtCode: string };

export const MANDAL_SEED: MandalSeed[] = [
  { code: 'agra', nameEn: 'Agra', nameHi: 'आगरा' },
  { code: 'aligarh', nameEn: 'Aligarh', nameHi: 'अलीगढ़' },
  { code: 'azamgarh', nameEn: 'Azamgarh', nameHi: 'आजमगढ़' },
  { code: 'bareilly', nameEn: 'Bareilly', nameHi: 'बरेली' },
  { code: 'basti', nameEn: 'Basti', nameHi: 'बस्ती' },
  { code: 'chitrakoot', nameEn: 'Chitrakoot', nameHi: 'चित्रकूट' },
  { code: 'devipatan', nameEn: 'Devipatan', nameHi: 'देवीपाटन' },
  { code: 'faizabad', nameEn: 'Ayodhya (Faizabad)', nameHi: 'अयोध्या (फैजाबाद)' },
  { code: 'gorakhpur', nameEn: 'Gorakhpur', nameHi: 'गोरखपुर' },
  { code: 'jhansi', nameEn: 'Jhansi', nameHi: 'झांसी' },
  { code: 'kanpur', nameEn: 'Kanpur', nameHi: 'कानपुर' },
  { code: 'lucknow', nameEn: 'Lucknow', nameHi: 'लखनऊ' },
  { code: 'meerut', nameEn: 'Meerut', nameHi: 'मेरठ' },
  { code: 'mirzapur', nameEn: 'Mirzapur (Vindhyachal)', nameHi: 'मिर्जापुर (विंध्याचल)' },
  { code: 'moradabad', nameEn: 'Moradabad', nameHi: 'मुरादाबाद' },
  { code: 'prayagraj', nameEn: 'Prayagraj', nameHi: 'प्रयागराज' },
  { code: 'saharanpur', nameEn: 'Saharanpur', nameHi: 'सहारनपुर' },
  { code: 'varanasi', nameEn: 'Varanasi', nameHi: 'वाराणसी' },
];

export const DISTRICT_SEED: DistrictSeed[] = [
  { code: 'D001', nameEn: 'Lucknow', nameHi: 'लखनऊ', mandalCode: 'lucknow' },
  { code: 'D002', nameEn: 'Varanasi', nameHi: 'वाराणसी', mandalCode: 'varanasi' },
  { code: 'D003', nameEn: 'Agra', nameHi: 'आगरा', mandalCode: 'agra' },
  { code: 'D004', nameEn: 'Aligarh', nameHi: 'अलीगढ़', mandalCode: 'aligarh' },
  { code: 'D005', nameEn: 'Ambedkar Nagar', nameHi: 'अंबेडकर नगर', mandalCode: 'faizabad' },
  { code: 'D006', nameEn: 'Amethi', nameHi: 'अमेठी', mandalCode: 'faizabad' },
  { code: 'D007', nameEn: 'Amroha', nameHi: 'अमरोहा', mandalCode: 'moradabad' },
  { code: 'D008', nameEn: 'Auraiya', nameHi: 'औरैया', mandalCode: 'kanpur' },
  { code: 'D009', nameEn: 'Ayodhya', nameHi: 'अयोध्या', mandalCode: 'faizabad' },
  { code: 'D010', nameEn: 'Azamgarh', nameHi: 'आजमगढ़', mandalCode: 'azamgarh' },
  { code: 'D011', nameEn: 'Baghpat', nameHi: 'बागपत', mandalCode: 'meerut' },
  { code: 'D012', nameEn: 'Bahraich', nameHi: 'बहराइच', mandalCode: 'devipatan' },
  { code: 'D013', nameEn: 'Ballia', nameHi: 'बलिया', mandalCode: 'azamgarh' },
  { code: 'D014', nameEn: 'Balrampur', nameHi: 'बलरामपुर', mandalCode: 'devipatan' },
  { code: 'D015', nameEn: 'Banda', nameHi: 'बांदा', mandalCode: 'chitrakoot' },
  { code: 'D016', nameEn: 'Bara Banki', nameHi: 'बाराबंकी', mandalCode: 'faizabad' },
  { code: 'D017', nameEn: 'Bareilly', nameHi: 'बरेली', mandalCode: 'bareilly' },
  { code: 'D018', nameEn: 'Basti', nameHi: 'बस्ती', mandalCode: 'basti' },
  { code: 'D019', nameEn: 'Bhadohi', nameHi: 'भदोही', mandalCode: 'mirzapur' },
  { code: 'D020', nameEn: 'Bijnor', nameHi: 'बिजनौर', mandalCode: 'moradabad' },
  { code: 'D021', nameEn: 'Budaun', nameHi: 'बदायूं', mandalCode: 'bareilly' },
  { code: 'D022', nameEn: 'Bulandshahr', nameHi: 'बुलंदशहर', mandalCode: 'meerut' },
  { code: 'D023', nameEn: 'Chandauli', nameHi: 'चंदौली', mandalCode: 'varanasi' },
  { code: 'D024', nameEn: 'Chitrakoot', nameHi: 'चित्रकूट', mandalCode: 'chitrakoot' },
  { code: 'D025', nameEn: 'Deoria', nameHi: 'देवरिया', mandalCode: 'gorakhpur' },
  { code: 'D026', nameEn: 'Etah', nameHi: 'एटा', mandalCode: 'aligarh' },
  { code: 'D027', nameEn: 'Etawah', nameHi: 'इटावा', mandalCode: 'kanpur' },
  { code: 'D028', nameEn: 'Farrukhabad', nameHi: 'फर्रुखाबाद', mandalCode: 'kanpur' },
  { code: 'D029', nameEn: 'Fatehpur', nameHi: 'फतेहपुर', mandalCode: 'prayagraj' },
  { code: 'D030', nameEn: 'Firozabad', nameHi: 'फ़िरोज़ाबाद', mandalCode: 'agra' },
  { code: 'D031', nameEn: 'Gautam Buddha Nagar', nameHi: 'गौतम बुद्ध नगर', mandalCode: 'meerut' },
  { code: 'D032', nameEn: 'Ghaziabad', nameHi: 'गाज़ियाबाद', mandalCode: 'meerut' },
  { code: 'D033', nameEn: 'Ghazipur', nameHi: 'गाज़ीपुर', mandalCode: 'varanasi' },
  { code: 'D034', nameEn: 'Gonda', nameHi: 'गोंडा', mandalCode: 'devipatan' },
  { code: 'D035', nameEn: 'Gorakhpur', nameHi: 'गोरखपुर', mandalCode: 'gorakhpur' },
  { code: 'D036', nameEn: 'Hamirpur', nameHi: 'हमीरपुर', mandalCode: 'chitrakoot' },
  { code: 'D037', nameEn: 'Hapur', nameHi: 'हापुड़', mandalCode: 'meerut' },
  { code: 'D038', nameEn: 'Hardoi', nameHi: 'हरदोई', mandalCode: 'lucknow' },
  { code: 'D039', nameEn: 'Hathras', nameHi: 'हाथरस', mandalCode: 'aligarh' },
  { code: 'D040', nameEn: 'Jalaun', nameHi: 'जालौन', mandalCode: 'jhansi' },
  { code: 'D041', nameEn: 'Jaunpur', nameHi: 'जौनपुर', mandalCode: 'varanasi' },
  { code: 'D042', nameEn: 'Jhansi', nameHi: 'झांसी', mandalCode: 'jhansi' },
  { code: 'D043', nameEn: 'Kannauj', nameHi: 'कन्नौज', mandalCode: 'kanpur' },
  { code: 'D044', nameEn: 'Kanpur Dehat', nameHi: 'कानपुर देहात', mandalCode: 'kanpur' },
  { code: 'D045', nameEn: 'Kanpur Nagar', nameHi: 'कानपुर नगर', mandalCode: 'kanpur' },
  { code: 'D046', nameEn: 'Kasganj', nameHi: 'कासगंज', mandalCode: 'aligarh' },
  { code: 'D047', nameEn: 'Kaushambi', nameHi: 'कौशाम्बी', mandalCode: 'prayagraj' },
  { code: 'D048', nameEn: 'Kheri', nameHi: 'लखीमपुर खीरी', mandalCode: 'lucknow' },
  { code: 'D049', nameEn: 'Kushinagar', nameHi: 'कुशीनगर', mandalCode: 'gorakhpur' },
  { code: 'D050', nameEn: 'Lalitpur', nameHi: 'ललितपुर', mandalCode: 'jhansi' },
  { code: 'D051', nameEn: 'Mahoba', nameHi: 'महोबा', mandalCode: 'chitrakoot' },
  { code: 'D052', nameEn: 'Mahrajganj', nameHi: 'महाराजगंज', mandalCode: 'gorakhpur' },
  { code: 'D053', nameEn: 'Mainpuri', nameHi: 'मैनपुरी', mandalCode: 'agra' },
  { code: 'D054', nameEn: 'Mathura', nameHi: 'मथुरा', mandalCode: 'agra' },
  { code: 'D055', nameEn: 'Mau', nameHi: 'मऊ', mandalCode: 'azamgarh' },
  { code: 'D056', nameEn: 'Meerut', nameHi: 'मेरठ', mandalCode: 'meerut' },
  { code: 'D057', nameEn: 'Mirzapur', nameHi: 'मिर्जापुर', mandalCode: 'mirzapur' },
  { code: 'D058', nameEn: 'Moradabad', nameHi: 'मुरादाबाद', mandalCode: 'moradabad' },
  { code: 'D059', nameEn: 'Muzaffarnagar', nameHi: 'मुजफ्फरनगर', mandalCode: 'saharanpur' },
  { code: 'D060', nameEn: 'Pilibhit', nameHi: 'पीलीभीत', mandalCode: 'bareilly' },
  { code: 'D061', nameEn: 'Pratapgarh', nameHi: 'प्रतापगढ़', mandalCode: 'prayagraj' },
  { code: 'D062', nameEn: 'Prayagraj', nameHi: 'प्रयागराज', mandalCode: 'prayagraj' },
  { code: 'D063', nameEn: 'Rae Bareli', nameHi: 'रायबरेली', mandalCode: 'lucknow' },
  { code: 'D064', nameEn: 'Rampur', nameHi: 'रामपुर', mandalCode: 'moradabad' },
  { code: 'D065', nameEn: 'Saharanpur', nameHi: 'सहारनपुर', mandalCode: 'saharanpur' },
  { code: 'D066', nameEn: 'Sambhal', nameHi: 'संभल', mandalCode: 'moradabad' },
  { code: 'D067', nameEn: 'Sant Kabir Nagar', nameHi: 'संत कबीर नगर', mandalCode: 'basti' },
  { code: 'D068', nameEn: 'Shahjahanpur', nameHi: 'शाहजहांपुर', mandalCode: 'bareilly' },
  { code: 'D069', nameEn: 'Shamli', nameHi: 'शामली', mandalCode: 'saharanpur' },
  { code: 'D070', nameEn: 'Shrawasti', nameHi: 'श्रावस्ती', mandalCode: 'devipatan' },
  { code: 'D071', nameEn: 'Siddharthnagar', nameHi: 'सिद्धार्थनगर', mandalCode: 'basti' },
  { code: 'D072', nameEn: 'Sitapur', nameHi: 'सीतापुर', mandalCode: 'lucknow' },
  { code: 'D073', nameEn: 'Sonbhadra', nameHi: 'सोनभद्र', mandalCode: 'mirzapur' },
  { code: 'D074', nameEn: 'Sultanpur', nameHi: 'सुल्तानपुर', mandalCode: 'faizabad' },
  { code: 'D075', nameEn: 'Unnao', nameHi: 'उन्नाव', mandalCode: 'lucknow' },
];

export const BLOCK_SEED: BlockSeedRow[] = [
  { code: 'B002', nameEn: 'Bakshi-Ka-Talab', nameHi: 'Bakshi-Ka-Talab', districtCode: 'D001' },
  { code: 'B005', nameEn: 'Chinhat', nameHi: 'Chinhat', districtCode: 'D001' },
  { code: 'B006', nameEn: 'Gosaiganj', nameHi: 'Gosaiganj', districtCode: 'D001' },
  { code: 'B007', nameEn: 'Kakori', nameHi: 'Kakori', districtCode: 'D001' },
  { code: 'B008', nameEn: 'Mal', nameHi: 'Mal', districtCode: 'D001' },
  { code: 'B009', nameEn: 'Malihabad', nameHi: 'Malihabad', districtCode: 'D001' },
  { code: 'B001', nameEn: 'Mohanlalganj', nameHi: 'Mohanlalganj', districtCode: 'D001' },
  { code: 'B010', nameEn: 'Sarojaninagar', nameHi: 'Sarojaninagar', districtCode: 'D001' },
  { code: 'B011', nameEn: 'Arajiline', nameHi: 'Arajiline', districtCode: 'D002' },
  { code: 'B012', nameEn: 'Baragaon', nameHi: 'Baragaon', districtCode: 'D002' },
  { code: 'B013', nameEn: 'Chiraigaon', nameHi: 'Chiraigaon', districtCode: 'D002' },
  { code: 'B014', nameEn: 'Cholapur', nameHi: 'Cholapur', districtCode: 'D002' },
  { code: 'B015', nameEn: 'Harahua', nameHi: 'Harahua', districtCode: 'D002' },
  { code: 'B016', nameEn: 'Kashi Vidyapeeth', nameHi: 'Kashi Vidyapeeth', districtCode: 'D002' },
  { code: 'B003', nameEn: 'Pindra', nameHi: 'Pindra', districtCode: 'D002' },
  { code: 'B004', nameEn: 'Sevapuri', nameHi: 'Sevapuri', districtCode: 'D002' },
  { code: 'B017', nameEn: 'Achhnera', nameHi: 'Achhnera', districtCode: 'D003' },
  { code: 'B018', nameEn: 'Akola', nameHi: 'Akola', districtCode: 'D003' },
  { code: 'B019', nameEn: 'Bah', nameHi: 'Bah', districtCode: 'D003' },
  { code: 'B020', nameEn: 'Barauli Ahir', nameHi: 'Barauli Ahir', districtCode: 'D003' },
  { code: 'B021', nameEn: 'Bichpuri', nameHi: 'Bichpuri', districtCode: 'D003' },
  { code: 'B022', nameEn: 'Etmadpur', nameHi: 'Etmadpur', districtCode: 'D003' },
  { code: 'B023', nameEn: 'Fatehabad', nameHi: 'Fatehabad', districtCode: 'D003' },
  { code: 'B024', nameEn: 'Fatehpur Sikri', nameHi: 'Fatehpur Sikri', districtCode: 'D003' },
  { code: 'B025', nameEn: 'Jagner', nameHi: 'Jagner', districtCode: 'D003' },
  { code: 'B026', nameEn: 'Jaitpur Kalan', nameHi: 'Jaitpur Kalan', districtCode: 'D003' },
  { code: 'B027', nameEn: 'Khandauli', nameHi: 'Khandauli', districtCode: 'D003' },
  { code: 'B028', nameEn: 'Kheragarh', nameHi: 'Kheragarh', districtCode: 'D003' },
  { code: 'B029', nameEn: 'Pinahat', nameHi: 'Pinahat', districtCode: 'D003' },
  { code: 'B030', nameEn: 'Saiyan', nameHi: 'Saiyan', districtCode: 'D003' },
  { code: 'B031', nameEn: 'Shamsabad', nameHi: 'Shamsabad', districtCode: 'D003' },
  { code: 'B032', nameEn: 'Akrabad', nameHi: 'Akrabad', districtCode: 'D004' },
  { code: 'B033', nameEn: 'Atrauli', nameHi: 'Atrauli', districtCode: 'D004' },
  { code: 'B034', nameEn: 'Bijauli', nameHi: 'Bijauli', districtCode: 'D004' },
  { code: 'B035', nameEn: 'Chandaus', nameHi: 'Chandaus', districtCode: 'D004' },
  { code: 'B036', nameEn: 'Dhanipur', nameHi: 'Dhanipur', districtCode: 'D004' },
  { code: 'B037', nameEn: 'Gangiri', nameHi: 'Gangiri', districtCode: 'D004' },
  { code: 'B038', nameEn: 'Gonda', nameHi: 'Gonda', districtCode: 'D004' },
  { code: 'B039', nameEn: 'Iglas', nameHi: 'Iglas', districtCode: 'D004' },
  { code: 'B040', nameEn: 'Jawan Sikanderpur', nameHi: 'Jawan Sikanderpur', districtCode: 'D004' },
  { code: 'B041', nameEn: 'Khair', nameHi: 'Khair', districtCode: 'D004' },
  { code: 'B042', nameEn: 'Lodha', nameHi: 'Lodha', districtCode: 'D004' },
  { code: 'B043', nameEn: 'Tappal', nameHi: 'Tappal', districtCode: 'D004' },
  { code: 'B044', nameEn: 'Akbarpur', nameHi: 'Akbarpur', districtCode: 'D005' },
  { code: 'B045', nameEn: 'Baskhari', nameHi: 'Baskhari', districtCode: 'D005' },
  { code: 'B046', nameEn: 'Bhiti', nameHi: 'Bhiti', districtCode: 'D005' },
  { code: 'B047', nameEn: 'Bhiyawan', nameHi: 'Bhiyawan', districtCode: 'D005' },
  { code: 'B048', nameEn: 'Jahangir Ganj', nameHi: 'Jahangir Ganj', districtCode: 'D005' },
  { code: 'B049', nameEn: 'Jalal Pur', nameHi: 'Jalal Pur', districtCode: 'D005' },
  { code: 'B050', nameEn: 'Katehari', nameHi: 'Katehari', districtCode: 'D005' },
  { code: 'B051', nameEn: 'Ram Nagar', nameHi: 'Ram Nagar', districtCode: 'D005' },
  { code: 'B052', nameEn: 'Tanda', nameHi: 'Tanda', districtCode: 'D005' },
  { code: 'B053', nameEn: 'Amethi', nameHi: 'Amethi', districtCode: 'D006' },
  { code: 'B054', nameEn: 'Bahadurpur', nameHi: 'Bahadurpur', districtCode: 'D006' },
  { code: 'B055', nameEn: 'Bhadar', nameHi: 'Bhadar', districtCode: 'D006' },
  { code: 'B056', nameEn: 'Bhetua', nameHi: 'Bhetua', districtCode: 'D006' },
  { code: 'B057', nameEn: 'Gauriganj', nameHi: 'Gauriganj', districtCode: 'D006' },
  { code: 'B058', nameEn: 'Jagdishpur', nameHi: 'Jagdishpur', districtCode: 'D006' },
  { code: 'B059', nameEn: 'Jamo', nameHi: 'Jamo', districtCode: 'D006' },
  { code: 'B060', nameEn: 'Musafir Khana', nameHi: 'Musafir Khana', districtCode: 'D006' },
  { code: 'B061', nameEn: 'Sangrampur', nameHi: 'Sangrampur', districtCode: 'D006' },
  { code: 'B062', nameEn: 'Shahgarh', nameHi: 'Shahgarh', districtCode: 'D006' },
  { code: 'B063', nameEn: 'Shukul Bazar', nameHi: 'Shukul Bazar', districtCode: 'D006' },
  { code: 'B064', nameEn: 'Singhpur', nameHi: 'Singhpur', districtCode: 'D006' },
  { code: 'B065', nameEn: 'Tiloi', nameHi: 'Tiloi', districtCode: 'D006' },
  { code: 'B066', nameEn: 'Amroha', nameHi: 'Amroha', districtCode: 'D007' },
  { code: 'B067', nameEn: 'Dhanaura', nameHi: 'Dhanaura', districtCode: 'D007' },
  { code: 'B068', nameEn: 'Gajraula', nameHi: 'Gajraula', districtCode: 'D007' },
  { code: 'B069', nameEn: 'Gangeshwari', nameHi: 'Gangeshwari', districtCode: 'D007' },
  { code: 'B070', nameEn: 'Hasanpur', nameHi: 'Hasanpur', districtCode: 'D007' },
  { code: 'B071', nameEn: 'Joya', nameHi: 'Joya', districtCode: 'D007' },
  { code: 'B072', nameEn: 'Achchalda', nameHi: 'Achchalda', districtCode: 'D008' },
  { code: 'B073', nameEn: 'Ajitmal', nameHi: 'Ajitmal', districtCode: 'D008' },
  { code: 'B074', nameEn: 'Auraiya', nameHi: 'Auraiya', districtCode: 'D008' },
  { code: 'B075', nameEn: 'Bhagyanagar', nameHi: 'Bhagyanagar', districtCode: 'D008' },
  { code: 'B076', nameEn: 'Bidhuna', nameHi: 'Bidhuna', districtCode: 'D008' },
  { code: 'B077', nameEn: 'Erwa Katra', nameHi: 'Erwa Katra', districtCode: 'D008' },
  { code: 'B078', nameEn: 'Sahar', nameHi: 'Sahar', districtCode: 'D008' },
  { code: 'B079', nameEn: 'Amaniganj', nameHi: 'Amaniganj', districtCode: 'D009' },
  { code: 'B080', nameEn: 'Bikapur', nameHi: 'Bikapur', districtCode: 'D009' },
  { code: 'B081', nameEn: 'Hariyangatanganj', nameHi: 'Hariyangatanganj', districtCode: 'D009' },
  { code: 'B082', nameEn: 'Masodha', nameHi: 'Masodha', districtCode: 'D009' },
  { code: 'B083', nameEn: 'Mawai', nameHi: 'Mawai', districtCode: 'D009' },
  { code: 'B084', nameEn: 'Maya Bazar', nameHi: 'Maya Bazar', districtCode: 'D009' },
  { code: 'B085', nameEn: 'Milkipur', nameHi: 'Milkipur', districtCode: 'D009' },
  { code: 'B086', nameEn: 'Pura Bazar', nameHi: 'Pura Bazar', districtCode: 'D009' },
  { code: 'B087', nameEn: 'Rudauli', nameHi: 'Rudauli', districtCode: 'D009' },
  { code: 'B088', nameEn: 'Sohawal', nameHi: 'Sohawal', districtCode: 'D009' },
  { code: 'B089', nameEn: 'Tarun', nameHi: 'Tarun', districtCode: 'D009' },
  { code: 'B090', nameEn: 'Ahiraula', nameHi: 'Ahiraula', districtCode: 'D010' },
  { code: 'B091', nameEn: 'Atraulia', nameHi: 'Atraulia', districtCode: 'D010' },
  { code: 'B092', nameEn: 'Azmatgarh', nameHi: 'Azmatgarh', districtCode: 'D010' },
  { code: 'B093', nameEn: 'Bilariyaganj', nameHi: 'Bilariyaganj', districtCode: 'D010' },
  { code: 'B094', nameEn: 'Haraiya', nameHi: 'Haraiya', districtCode: 'D010' },
  { code: 'B095', nameEn: 'Jahanaganj', nameHi: 'Jahanaganj', districtCode: 'D010' },
  { code: 'B096', nameEn: 'Koilsa', nameHi: 'Koilsa', districtCode: 'D010' },
  { code: 'B097', nameEn: 'Lalganj', nameHi: 'Lalganj', districtCode: 'D010' },
  { code: 'B098', nameEn: 'Mahrajganj', nameHi: 'Mahrajganj', districtCode: 'D010' },
  { code: 'B099', nameEn: 'Martinganj', nameHi: 'Martinganj', districtCode: 'D010' },
  { code: 'B100', nameEn: 'Mehnagar', nameHi: 'Mehnagar', districtCode: 'D010' },
  { code: 'B101', nameEn: 'Mirzapur', nameHi: 'Mirzapur', districtCode: 'D010' },
  { code: 'B102', nameEn: 'Mohammadpur', nameHi: 'Mohammadpur', districtCode: 'D010' },
  { code: 'B103', nameEn: 'Palhana', nameHi: 'Palhana', districtCode: 'D010' },
  { code: 'B104', nameEn: 'Palhani', nameHi: 'Palhani', districtCode: 'D010' },
  { code: 'B105', nameEn: 'Pawai', nameHi: 'Pawai', districtCode: 'D010' },
  { code: 'B106', nameEn: 'Phulpur', nameHi: 'Phulpur', districtCode: 'D010' },
  { code: 'B107', nameEn: 'Rani Ki Sarai', nameHi: 'Rani Ki Sarai', districtCode: 'D010' },
  { code: 'B108', nameEn: 'Sathiyaon', nameHi: 'Sathiyaon', districtCode: 'D010' },
  { code: 'B109', nameEn: 'Tahbarpur', nameHi: 'Tahbarpur', districtCode: 'D010' },
  { code: 'B110', nameEn: 'Tarwa', nameHi: 'Tarwa', districtCode: 'D010' },
  { code: 'B111', nameEn: 'Thekma', nameHi: 'Thekma', districtCode: 'D010' },
  { code: 'B112', nameEn: 'Baghpat', nameHi: 'Baghpat', districtCode: 'D011' },
  { code: 'B113', nameEn: 'Baraut', nameHi: 'Baraut', districtCode: 'D011' },
  { code: 'B114', nameEn: 'Binauli', nameHi: 'Binauli', districtCode: 'D011' },
  { code: 'B115', nameEn: 'Chhaprauli', nameHi: 'Chhaprauli', districtCode: 'D011' },
  { code: 'B116', nameEn: 'Khekra', nameHi: 'Khekra', districtCode: 'D011' },
  { code: 'B117', nameEn: 'Pilana', nameHi: 'Pilana', districtCode: 'D011' },
  { code: 'B118', nameEn: 'Balaha', nameHi: 'Balaha', districtCode: 'D012' },
  { code: 'B119', nameEn: 'Chitaura', nameHi: 'Chitaura', districtCode: 'D012' },
  { code: 'B120', nameEn: 'Huzoorpur', nameHi: 'Huzoorpur', districtCode: 'D012' },
  { code: 'B121', nameEn: 'Jarwal', nameHi: 'Jarwal', districtCode: 'D012' },
  { code: 'B122', nameEn: 'Kaisarganj', nameHi: 'Kaisarganj', districtCode: 'D012' },
  { code: 'B123', nameEn: 'Mahasi', nameHi: 'Mahasi', districtCode: 'D012' },
  { code: 'B124', nameEn: 'Mihinpurwa', nameHi: 'Mihinpurwa', districtCode: 'D012' },
  { code: 'B125', nameEn: 'Nawabganj', nameHi: 'Nawabganj', districtCode: 'D012' },
  { code: 'B126', nameEn: 'Payagpur', nameHi: 'Payagpur', districtCode: 'D012' },
  { code: 'B127', nameEn: 'Phakharpur', nameHi: 'Phakharpur', districtCode: 'D012' },
  { code: 'B128', nameEn: 'Risia', nameHi: 'Risia', districtCode: 'D012' },
  { code: 'B129', nameEn: 'Shivpur', nameHi: 'Shivpur', districtCode: 'D012' },
  { code: 'B130', nameEn: 'Tejwapur', nameHi: 'Tejwapur', districtCode: 'D012' },
  { code: 'B131', nameEn: 'Visheshwarganj', nameHi: 'Visheshwarganj', districtCode: 'D012' },
  { code: 'B132', nameEn: 'Bairia', nameHi: 'Bairia', districtCode: 'D013' },
  { code: 'B133', nameEn: 'Bansdih', nameHi: 'Bansdih', districtCode: 'D013' },
  { code: 'B134', nameEn: 'Belhari', nameHi: 'Belhari', districtCode: 'D013' },
  { code: 'B135', nameEn: 'Beruarbari', nameHi: 'Beruarbari', districtCode: 'D013' },
  { code: 'B136', nameEn: 'Chilkahar', nameHi: 'Chilkahar', districtCode: 'D013' },
  { code: 'B137', nameEn: 'Dubhar', nameHi: 'Dubhar', districtCode: 'D013' },
  { code: 'B138', nameEn: 'Garwar', nameHi: 'Garwar', districtCode: 'D013' },
  { code: 'B139', nameEn: 'Hanumanganj', nameHi: 'Hanumanganj', districtCode: 'D013' },
  { code: 'B140', nameEn: 'Maniar', nameHi: 'Maniar', districtCode: 'D013' },
  { code: 'B141', nameEn: 'Murlichhapra', nameHi: 'Murlichhapra', districtCode: 'D013' },
  { code: 'B142', nameEn: 'Nagra', nameHi: 'Nagra', districtCode: 'D013' },
  { code: 'B143', nameEn: 'Navanagar', nameHi: 'Navanagar', districtCode: 'D013' },
  { code: 'B144', nameEn: 'Pandah', nameHi: 'Pandah', districtCode: 'D013' },
  { code: 'B145', nameEn: 'Rasra', nameHi: 'Rasra', districtCode: 'D013' },
  { code: 'B146', nameEn: 'Reoti', nameHi: 'Reoti', districtCode: 'D013' },
  { code: 'B147', nameEn: 'Siar', nameHi: 'Siar', districtCode: 'D013' },
  { code: 'B148', nameEn: 'Sohanv', nameHi: 'Sohanv', districtCode: 'D013' },
  { code: 'B149', nameEn: 'Balrampur', nameHi: 'Balrampur', districtCode: 'D014' },
  { code: 'B150', nameEn: 'Gaindas Bujurg', nameHi: 'Gaindas Bujurg', districtCode: 'D014' },
  { code: 'B151', nameEn: 'Gaisri', nameHi: 'Gaisri', districtCode: 'D014' },
  { code: 'B152', nameEn: 'Harriya Satgharwa', nameHi: 'Harriya Satgharwa', districtCode: 'D014' },
  { code: 'B153', nameEn: 'Pachpedwa', nameHi: 'Pachpedwa', districtCode: 'D014' },
  { code: 'B154', nameEn: 'Rehera Bazaar', nameHi: 'Rehera Bazaar', districtCode: 'D014' },
  { code: 'B155', nameEn: 'Shriduttganj', nameHi: 'Shriduttganj', districtCode: 'D014' },
  { code: 'B156', nameEn: 'Tulsipur', nameHi: 'Tulsipur', districtCode: 'D014' },
  { code: 'B157', nameEn: 'Utraula', nameHi: 'Utraula', districtCode: 'D014' },
  { code: 'B158', nameEn: 'Baberu', nameHi: 'Baberu', districtCode: 'D015' },
  { code: 'B159', nameEn: 'Badokhar Khurd', nameHi: 'Badokhar Khurd', districtCode: 'D015' },
  { code: 'B160', nameEn: 'Bisanda', nameHi: 'Bisanda', districtCode: 'D015' },
  { code: 'B161', nameEn: 'Jaspura', nameHi: 'Jaspura', districtCode: 'D015' },
  { code: 'B162', nameEn: 'Kamasin', nameHi: 'Kamasin', districtCode: 'D015' },
  { code: 'B163', nameEn: 'Mahuva', nameHi: 'Mahuva', districtCode: 'D015' },
  { code: 'B164', nameEn: 'Naraini', nameHi: 'Naraini', districtCode: 'D015' },
  { code: 'B165', nameEn: 'Tindwari', nameHi: 'Tindwari', districtCode: 'D015' },
  { code: 'B166', nameEn: 'Bani Kodar', nameHi: 'Bani Kodar', districtCode: 'D016' },
  { code: 'B167', nameEn: 'Banki', nameHi: 'Banki', districtCode: 'D016' },
  { code: 'B168', nameEn: 'Dariyabad', nameHi: 'Dariyabad', districtCode: 'D016' },
  { code: 'B169', nameEn: 'Dewa', nameHi: 'Dewa', districtCode: 'D016' },
  { code: 'B170', nameEn: 'Fatehpur', nameHi: 'Fatehpur', districtCode: 'D016' },
  { code: 'B171', nameEn: 'Haidargarh', nameHi: 'Haidargarh', districtCode: 'D016' },
  { code: 'B172', nameEn: 'Harakh', nameHi: 'Harakh', districtCode: 'D016' },
  { code: 'B173', nameEn: 'Masauli', nameHi: 'Masauli', districtCode: 'D016' },
  { code: 'B174', nameEn: 'Nindaura', nameHi: 'Nindaura', districtCode: 'D016' },
  { code: 'B175', nameEn: 'Puredalai', nameHi: 'Puredalai', districtCode: 'D016' },
  { code: 'B176', nameEn: 'Ramnagar', nameHi: 'Ramnagar', districtCode: 'D016' },
  { code: 'B177', nameEn: 'Sidhaur', nameHi: 'Sidhaur', districtCode: 'D016' },
  { code: 'B178', nameEn: 'Sirauli Gauspur', nameHi: 'Sirauli Gauspur', districtCode: 'D016' },
  { code: 'B179', nameEn: 'Suratganj', nameHi: 'Suratganj', districtCode: 'D016' },
  { code: 'B180', nameEn: 'Trivediganj', nameHi: 'Trivediganj', districtCode: 'D016' },
  { code: 'B181', nameEn: 'Aalampur Jafarabad', nameHi: 'Aalampur Jafarabad', districtCode: 'D017' },
  { code: 'B182', nameEn: 'Baheri', nameHi: 'Baheri', districtCode: 'D017' },
  { code: 'B183', nameEn: 'Bhadpura', nameHi: 'Bhadpura', districtCode: 'D017' },
  { code: 'B184', nameEn: 'Bhojipura', nameHi: 'Bhojipura', districtCode: 'D017' },
  { code: 'B185', nameEn: 'Bhuta', nameHi: 'Bhuta', districtCode: 'D017' },
  { code: 'B186', nameEn: 'Bithiri Chainpur', nameHi: 'Bithiri Chainpur', districtCode: 'D017' },
  { code: 'B187', nameEn: 'Damkhauda', nameHi: 'Damkhauda', districtCode: 'D017' },
  { code: 'B188', nameEn: 'Faridpur', nameHi: 'Faridpur', districtCode: 'D017' },
  { code: 'B189', nameEn: 'Fatehganj West', nameHi: 'Fatehganj West', districtCode: 'D017' },
  { code: 'B190', nameEn: 'Kyara', nameHi: 'Kyara', districtCode: 'D017' },
  { code: 'B191', nameEn: 'Majhgawan', nameHi: 'Majhgawan', districtCode: 'D017' },
  { code: 'B192', nameEn: 'Mirganj', nameHi: 'Mirganj', districtCode: 'D017' },
  { code: 'B193', nameEn: 'Nawabganj', nameHi: 'Nawabganj', districtCode: 'D017' },
  { code: 'B194', nameEn: 'Ramnagar', nameHi: 'Ramnagar', districtCode: 'D017' },
  { code: 'B195', nameEn: 'Shergarh', nameHi: 'Shergarh', districtCode: 'D017' },
  { code: 'B196', nameEn: 'Bahadurpur', nameHi: 'Bahadurpur', districtCode: 'D018' },
  { code: 'B197', nameEn: 'Bankati', nameHi: 'Bankati', districtCode: 'D018' },
  { code: 'B198', nameEn: 'Basti', nameHi: 'Basti', districtCode: 'D018' },
  { code: 'B199', nameEn: 'Dubauliya', nameHi: 'Dubauliya', districtCode: 'D018' },
  { code: 'B200', nameEn: 'Gaur', nameHi: 'Gaur', districtCode: 'D018' },
  { code: 'B201', nameEn: 'Harraiya', nameHi: 'Harraiya', districtCode: 'D018' },
  { code: 'B202', nameEn: 'Kaptanganj', nameHi: 'Kaptanganj', districtCode: 'D018' },
  { code: 'B203', nameEn: 'Kudaraha', nameHi: 'Kudaraha', districtCode: 'D018' },
  { code: 'B204', nameEn: 'Paras Rampur', nameHi: 'Paras Rampur', districtCode: 'D018' },
  { code: 'B205', nameEn: 'Ramnagar', nameHi: 'Ramnagar', districtCode: 'D018' },
  { code: 'B206', nameEn: 'Rudauli', nameHi: 'Rudauli', districtCode: 'D018' },
  { code: 'B207', nameEn: 'Saltaua Gopal Pur', nameHi: 'Saltaua Gopal Pur', districtCode: 'D018' },
  { code: 'B208', nameEn: 'Sau Ghat', nameHi: 'Sau Ghat', districtCode: 'D018' },
  { code: 'B209', nameEn: 'Vikram Jot', nameHi: 'Vikram Jot', districtCode: 'D018' },
  { code: 'B210', nameEn: 'Abhauli', nameHi: 'Abhauli', districtCode: 'D019' },
  { code: 'B211', nameEn: 'Aurai', nameHi: 'Aurai', districtCode: 'D019' },
  { code: 'B212', nameEn: 'Bhadohi', nameHi: 'Bhadohi', districtCode: 'D019' },
  { code: 'B213', nameEn: 'Deegh', nameHi: 'Deegh', districtCode: 'D019' },
  { code: 'B214', nameEn: 'Gyanpur', nameHi: 'Gyanpur', districtCode: 'D019' },
  { code: 'B215', nameEn: 'Suriyavan', nameHi: 'Suriyavan', districtCode: 'D019' },
  { code: 'B216', nameEn: 'Afzalgarh', nameHi: 'Afzalgarh', districtCode: 'D020' },
  { code: 'B217', nameEn: 'Budhanpur Seohara', nameHi: 'Budhanpur Seohara', districtCode: 'D020' },
  { code: 'B218', nameEn: 'Dhampur', nameHi: 'Dhampur', districtCode: 'D020' },
  { code: 'B219', nameEn: 'Haldaur(Khari Jhalu)', nameHi: 'Haldaur(Khari Jhalu)', districtCode: 'D020' },
  { code: 'B220', nameEn: 'Jalilpur', nameHi: 'Jalilpur', districtCode: 'D020' },
  { code: 'B221', nameEn: 'Kiratpur', nameHi: 'Kiratpur', districtCode: 'D020' },
  { code: 'B222', nameEn: 'Kotwali', nameHi: 'Kotwali', districtCode: 'D020' },
  { code: 'B223', nameEn: 'Mohammedpur Deomal', nameHi: 'Mohammedpur Deomal', districtCode: 'D020' },
  { code: 'B224', nameEn: 'Najibabad', nameHi: 'Najibabad', districtCode: 'D020' },
  { code: 'B225', nameEn: 'Nehtaur', nameHi: 'Nehtaur', districtCode: 'D020' },
  { code: 'B226', nameEn: 'Noorpur', nameHi: 'Noorpur', districtCode: 'D020' },
  { code: 'B227', nameEn: 'Ambiapur', nameHi: 'Ambiapur', districtCode: 'D021' },
  { code: 'B228', nameEn: 'Asafpur', nameHi: 'Asafpur', districtCode: 'D021' },
  { code: 'B229', nameEn: 'Bisauli', nameHi: 'Bisauli', districtCode: 'D021' },
  { code: 'B230', nameEn: 'Dahgavan', nameHi: 'Dahgavan', districtCode: 'D021' },
  { code: 'B231', nameEn: 'Dataganj', nameHi: 'Dataganj', districtCode: 'D021' },
  { code: 'B232', nameEn: 'Islamnagar', nameHi: 'Islamnagar', districtCode: 'D021' },
  { code: 'B233', nameEn: 'Jagat', nameHi: 'Jagat', districtCode: 'D021' },
  { code: 'B234', nameEn: 'Mion', nameHi: 'Mion', districtCode: 'D021' },
  { code: 'B235', nameEn: 'Qadar Chowk', nameHi: 'Qadar Chowk', districtCode: 'D021' },
  { code: 'B236', nameEn: 'Sahaswan', nameHi: 'Sahaswan', districtCode: 'D021' },
  { code: 'B237', nameEn: 'Salarpur', nameHi: 'Salarpur', districtCode: 'D021' },
  { code: 'B238', nameEn: 'Samrer', nameHi: 'Samrer', districtCode: 'D021' },
  { code: 'B239', nameEn: 'Ujhani', nameHi: 'Ujhani', districtCode: 'D021' },
  { code: 'B240', nameEn: 'Usawan', nameHi: 'Usawan', districtCode: 'D021' },
  { code: 'B241', nameEn: 'Wazirganj', nameHi: 'Wazirganj', districtCode: 'D021' },
  { code: 'B242', nameEn: 'Agauta', nameHi: 'Agauta', districtCode: 'D022' },
  { code: 'B243', nameEn: 'Anupshahr', nameHi: 'Anupshahr', districtCode: 'D022' },
  { code: 'B244', nameEn: 'Araniya', nameHi: 'Araniya', districtCode: 'D022' },
  { code: 'B245', nameEn: 'Bhawan Bahadur Nagar', nameHi: 'Bhawan Bahadur Nagar', districtCode: 'D022' },
  { code: 'B246', nameEn: 'Bulandshahr', nameHi: 'Bulandshahr', districtCode: 'D022' },
  { code: 'B247', nameEn: 'Danpur', nameHi: 'Danpur', districtCode: 'D022' },
  { code: 'B248', nameEn: 'Dibai', nameHi: 'Dibai', districtCode: 'D022' },
  { code: 'B249', nameEn: 'Gulaothi', nameHi: 'Gulaothi', districtCode: 'D022' },
  { code: 'B250', nameEn: 'Jahangirabad', nameHi: 'Jahangirabad', districtCode: 'D022' },
  { code: 'B251', nameEn: 'Khurja', nameHi: 'Khurja', districtCode: 'D022' },
  { code: 'B252', nameEn: 'Lakhaothi', nameHi: 'Lakhaothi', districtCode: 'D022' },
  { code: 'B253', nameEn: 'Pahasu', nameHi: 'Pahasu', districtCode: 'D022' },
  { code: 'B254', nameEn: 'Shikarpur', nameHi: 'Shikarpur', districtCode: 'D022' },
  { code: 'B255', nameEn: 'Sikandrabad', nameHi: 'Sikandrabad', districtCode: 'D022' },
  { code: 'B256', nameEn: 'Syana', nameHi: 'Syana', districtCode: 'D022' },
  { code: 'B257', nameEn: 'Unchagaon', nameHi: 'Unchagaon', districtCode: 'D022' },
  { code: 'B258', nameEn: 'Berahani', nameHi: 'Berahani', districtCode: 'D023' },
  { code: 'B259', nameEn: 'Chahniya', nameHi: 'Chahniya', districtCode: 'D023' },
  { code: 'B260', nameEn: 'Chakiya', nameHi: 'Chakiya', districtCode: 'D023' },
  { code: 'B261', nameEn: 'Chandauli', nameHi: 'Chandauli', districtCode: 'D023' },
  { code: 'B262', nameEn: 'Dhanapur', nameHi: 'Dhanapur', districtCode: 'D023' },
  { code: 'B263', nameEn: 'Naugarh', nameHi: 'Naugarh', districtCode: 'D023' },
  { code: 'B264', nameEn: 'Niyamatabad', nameHi: 'Niyamatabad', districtCode: 'D023' },
  { code: 'B265', nameEn: 'Sahabganj', nameHi: 'Sahabganj', districtCode: 'D023' },
  { code: 'B266', nameEn: 'Sakaldiha', nameHi: 'Sakaldiha', districtCode: 'D023' },
  { code: 'B267', nameEn: 'Karwi', nameHi: 'Karwi', districtCode: 'D024' },
  { code: 'B268', nameEn: 'Manikpur', nameHi: 'Manikpur', districtCode: 'D024' },
  { code: 'B269', nameEn: 'Mau', nameHi: 'Mau', districtCode: 'D024' },
  { code: 'B270', nameEn: 'Pahari', nameHi: 'Pahari', districtCode: 'D024' },
  { code: 'B271', nameEn: 'Ramnagar', nameHi: 'Ramnagar', districtCode: 'D024' },
  { code: 'B272', nameEn: 'Baitalpur', nameHi: 'Baitalpur', districtCode: 'D025' },
  { code: 'B273', nameEn: 'Bankata', nameHi: 'Bankata', districtCode: 'D025' },
  { code: 'B274', nameEn: 'Barhaj', nameHi: 'Barhaj', districtCode: 'D025' },
  { code: 'B275', nameEn: 'Bhagalpur', nameHi: 'Bhagalpur', districtCode: 'D025' },
  { code: 'B276', nameEn: 'Bhaluani', nameHi: 'Bhaluani', districtCode: 'D025' },
  { code: 'B277', nameEn: 'Bhatni', nameHi: 'Bhatni', districtCode: 'D025' },
  { code: 'B278', nameEn: 'Bhatpar Rani', nameHi: 'Bhatpar Rani', districtCode: 'D025' },
  { code: 'B279', nameEn: 'Deoria Sadar', nameHi: 'Deoria Sadar', districtCode: 'D025' },
  { code: 'B280', nameEn: 'Desai Deoria', nameHi: 'Desai Deoria', districtCode: 'D025' },
  { code: 'B281', nameEn: 'Gauri Bazar', nameHi: 'Gauri Bazar', districtCode: 'D025' },
  { code: 'B282', nameEn: 'Lar', nameHi: 'Lar', districtCode: 'D025' },
  { code: 'B283', nameEn: 'Pathar Dewa', nameHi: 'Pathar Dewa', districtCode: 'D025' },
  { code: 'B284', nameEn: 'Rampur Karkhana', nameHi: 'Rampur Karkhana', districtCode: 'D025' },
  { code: 'B285', nameEn: 'Rudrapur', nameHi: 'Rudrapur', districtCode: 'D025' },
  { code: 'B286', nameEn: 'Salempur', nameHi: 'Salempur', districtCode: 'D025' },
  { code: 'B287', nameEn: 'Tarkalua', nameHi: 'Tarkalua', districtCode: 'D025' },
  { code: 'B288', nameEn: 'Aliganj', nameHi: 'Aliganj', districtCode: 'D026' },
  { code: 'B289', nameEn: 'Awagarh', nameHi: 'Awagarh', districtCode: 'D026' },
  { code: 'B290', nameEn: 'Jaithara', nameHi: 'Jaithara', districtCode: 'D026' },
  { code: 'B291', nameEn: 'Jalesar', nameHi: 'Jalesar', districtCode: 'D026' },
  { code: 'B292', nameEn: 'Marehra', nameHi: 'Marehra', districtCode: 'D026' },
  { code: 'B293', nameEn: 'Nidhauli Kalan', nameHi: 'Nidhauli Kalan', districtCode: 'D026' },
  { code: 'B294', nameEn: 'Sakit', nameHi: 'Sakit', districtCode: 'D026' },
  { code: 'B295', nameEn: 'Shitalpur', nameHi: 'Shitalpur', districtCode: 'D026' },
  { code: 'B296', nameEn: 'Barhpura', nameHi: 'Barhpura', districtCode: 'D027' },
  { code: 'B297', nameEn: 'Basrehar', nameHi: 'Basrehar', districtCode: 'D027' },
  { code: 'B298', nameEn: 'Bharthana', nameHi: 'Bharthana', districtCode: 'D027' },
  { code: 'B299', nameEn: 'Chakarnagar', nameHi: 'Chakarnagar', districtCode: 'D027' },
  { code: 'B300', nameEn: 'Jaswantnagar', nameHi: 'Jaswantnagar', districtCode: 'D027' },
  { code: 'B301', nameEn: 'Mahewa', nameHi: 'Mahewa', districtCode: 'D027' },
  { code: 'B302', nameEn: 'Sefai', nameHi: 'Sefai', districtCode: 'D027' },
  { code: 'B303', nameEn: 'Takha', nameHi: 'Takha', districtCode: 'D027' },
  { code: 'B304', nameEn: 'Barhpur', nameHi: 'Barhpur', districtCode: 'D028' },
  { code: 'B305', nameEn: 'Kaimganj', nameHi: 'Kaimganj', districtCode: 'D028' },
  { code: 'B306', nameEn: 'Kamalganj', nameHi: 'Kamalganj', districtCode: 'D028' },
  { code: 'B307', nameEn: 'Mohamdabad', nameHi: 'Mohamdabad', districtCode: 'D028' },
  { code: 'B308', nameEn: 'Nawabganj', nameHi: 'Nawabganj', districtCode: 'D028' },
  { code: 'B309', nameEn: 'Rajepur', nameHi: 'Rajepur', districtCode: 'D028' },
  { code: 'B310', nameEn: 'Shamsabad', nameHi: 'Shamsabad', districtCode: 'D028' },
  { code: 'B311', nameEn: 'Airayan', nameHi: 'Airayan', districtCode: 'D029' },
  { code: 'B312', nameEn: 'Amauli', nameHi: 'Amauli', districtCode: 'D029' },
  { code: 'B313', nameEn: 'Asothar', nameHi: 'Asothar', districtCode: 'D029' },
  { code: 'B314', nameEn: 'Bahua', nameHi: 'Bahua', districtCode: 'D029' },
  { code: 'B315', nameEn: 'Bhitaura', nameHi: 'Bhitaura', districtCode: 'D029' },
  { code: 'B316', nameEn: 'Devmai', nameHi: 'Devmai', districtCode: 'D029' },
  { code: 'B317', nameEn: 'Dhata', nameHi: 'Dhata', districtCode: 'D029' },
  { code: 'B318', nameEn: 'Haswa', nameHi: 'Haswa', districtCode: 'D029' },
  { code: 'B319', nameEn: 'Hathgaon', nameHi: 'Hathgaon', districtCode: 'D029' },
  { code: 'B320', nameEn: 'Khajuha', nameHi: 'Khajuha', districtCode: 'D029' },
  { code: 'B321', nameEn: 'Malwan', nameHi: 'Malwan', districtCode: 'D029' },
  { code: 'B322', nameEn: 'Telyani', nameHi: 'Telyani', districtCode: 'D029' },
  { code: 'B323', nameEn: 'Vijayipur', nameHi: 'Vijayipur', districtCode: 'D029' },
  { code: 'B324', nameEn: 'Araon', nameHi: 'Araon', districtCode: 'D030' },
  { code: 'B325', nameEn: 'Eka', nameHi: 'Eka', districtCode: 'D030' },
  { code: 'B326', nameEn: 'Firozabad', nameHi: 'Firozabad', districtCode: 'D030' },
  { code: 'B327', nameEn: 'Hathwant', nameHi: 'Hathwant', districtCode: 'D030' },
  { code: 'B328', nameEn: 'Jasrana', nameHi: 'Jasrana', districtCode: 'D030' },
  { code: 'B329', nameEn: 'Madanpur', nameHi: 'Madanpur', districtCode: 'D030' },
  { code: 'B330', nameEn: 'Narkhi', nameHi: 'Narkhi', districtCode: 'D030' },
  { code: 'B331', nameEn: 'Shikohabad', nameHi: 'Shikohabad', districtCode: 'D030' },
  { code: 'B332', nameEn: 'Tundla', nameHi: 'Tundla', districtCode: 'D030' },
  { code: 'B333', nameEn: 'Bisrakh', nameHi: 'Bisrakh', districtCode: 'D031' },
  { code: 'B334', nameEn: 'Dadri', nameHi: 'Dadri', districtCode: 'D031' },
  { code: 'B335', nameEn: 'Jewar', nameHi: 'Jewar', districtCode: 'D031' },
  { code: 'B336', nameEn: 'Bhojpur', nameHi: 'Bhojpur', districtCode: 'D032' },
  { code: 'B337', nameEn: 'Loni', nameHi: 'Loni', districtCode: 'D032' },
  { code: 'B338', nameEn: 'Muradnagar', nameHi: 'Muradnagar', districtCode: 'D032' },
  { code: 'B339', nameEn: 'Rajapur', nameHi: 'Rajapur', districtCode: 'D032' },
  { code: 'B340', nameEn: 'Bhadaura', nameHi: 'Bhadaura', districtCode: 'D033' },
  { code: 'B341', nameEn: 'Bhanwarkol', nameHi: 'Bhanwarkol', districtCode: 'D033' },
  { code: 'B342', nameEn: 'Devkali', nameHi: 'Devkali', districtCode: 'D033' },
  { code: 'B343', nameEn: 'Ghazipur', nameHi: 'Ghazipur', districtCode: 'D033' },
  { code: 'B344', nameEn: 'Jakhania', nameHi: 'Jakhania', districtCode: 'D033' },
  { code: 'B345', nameEn: 'Karanda', nameHi: 'Karanda', districtCode: 'D033' },
  { code: 'B346', nameEn: 'Kasimabad', nameHi: 'Kasimabad', districtCode: 'D033' },
  { code: 'B347', nameEn: 'Manihari', nameHi: 'Manihari', districtCode: 'D033' },
  { code: 'B348', nameEn: 'Mardah', nameHi: 'Mardah', districtCode: 'D033' },
  { code: 'B349', nameEn: 'Mohammadabad', nameHi: 'Mohammadabad', districtCode: 'D033' },
  { code: 'B350', nameEn: 'Revatipur', nameHi: 'Revatipur', districtCode: 'D033' },
  { code: 'B351', nameEn: 'Sadat', nameHi: 'Sadat', districtCode: 'D033' },
  { code: 'B352', nameEn: 'Saidpur', nameHi: 'Saidpur', districtCode: 'D033' },
  { code: 'B353', nameEn: 'Varachakwar', nameHi: 'Varachakwar', districtCode: 'D033' },
  { code: 'B354', nameEn: 'Virno', nameHi: 'Virno', districtCode: 'D033' },
  { code: 'B355', nameEn: 'Zamania', nameHi: 'Zamania', districtCode: 'D033' },
  { code: 'B356', nameEn: 'Babhanjot', nameHi: 'Babhanjot', districtCode: 'D034' },
  { code: 'B357', nameEn: 'Belsar', nameHi: 'Belsar', districtCode: 'D034' },
  { code: 'B358', nameEn: 'Chhapia', nameHi: 'Chhapia', districtCode: 'D034' },
  { code: 'B359', nameEn: 'Colonelganj', nameHi: 'Colonelganj', districtCode: 'D034' },
  { code: 'B360', nameEn: 'Haldharmau', nameHi: 'Haldharmau', districtCode: 'D034' },
  { code: 'B361', nameEn: 'Itiathok', nameHi: 'Itiathok', districtCode: 'D034' },
  { code: 'B362', nameEn: 'Jhanjhari', nameHi: 'Jhanjhari', districtCode: 'D034' },
  { code: 'B363', nameEn: 'Katra Bazar', nameHi: 'Katra Bazar', districtCode: 'D034' },
  { code: 'B364', nameEn: 'Mankapur', nameHi: 'Mankapur', districtCode: 'D034' },
  { code: 'B365', nameEn: 'Mujehana', nameHi: 'Mujehana', districtCode: 'D034' },
  { code: 'B366', nameEn: 'Nawabganj', nameHi: 'Nawabganj', districtCode: 'D034' },
  { code: 'B367', nameEn: 'Pandri Kripal', nameHi: 'Pandri Kripal', districtCode: 'D034' },
  { code: 'B368', nameEn: 'Paraspur', nameHi: 'Paraspur', districtCode: 'D034' },
  { code: 'B369', nameEn: 'Rupaideeh', nameHi: 'Rupaideeh', districtCode: 'D034' },
  { code: 'B370', nameEn: 'Tarabganj', nameHi: 'Tarabganj', districtCode: 'D034' },
  { code: 'B371', nameEn: 'Wazirganj', nameHi: 'Wazirganj', districtCode: 'D034' },
  { code: 'B372', nameEn: 'Bansgaon', nameHi: 'Bansgaon', districtCode: 'D035' },
  { code: 'B373', nameEn: 'Barhalganj', nameHi: 'Barhalganj', districtCode: 'D035' },
  { code: 'B374', nameEn: 'Belghat', nameHi: 'Belghat', districtCode: 'D035' },
  { code: 'B375', nameEn: 'Bharohiya', nameHi: 'Bharohiya', districtCode: 'D035' },
  { code: 'B376', nameEn: 'Bhathat', nameHi: 'Bhathat', districtCode: 'D035' },
  { code: 'B377', nameEn: 'Brahmpur', nameHi: 'Brahmpur', districtCode: 'D035' },
  { code: 'B378', nameEn: 'Campierganj', nameHi: 'Campierganj', districtCode: 'D035' },
  { code: 'B379', nameEn: 'Chargawan', nameHi: 'Chargawan', districtCode: 'D035' },
  { code: 'B380', nameEn: 'Gagaha', nameHi: 'Gagaha', districtCode: 'D035' },
  { code: 'B381', nameEn: 'Gola', nameHi: 'Gola', districtCode: 'D035' },
  { code: 'B382', nameEn: 'Jangal Kaudia', nameHi: 'Jangal Kaudia', districtCode: 'D035' },
  { code: 'B383', nameEn: 'Kauri Ram', nameHi: 'Kauri Ram', districtCode: 'D035' },
  { code: 'B384', nameEn: 'Khajni', nameHi: 'Khajni', districtCode: 'D035' },
  { code: 'B385', nameEn: 'Khorabar', nameHi: 'Khorabar', districtCode: 'D035' },
  { code: 'B386', nameEn: 'Pali', nameHi: 'Pali', districtCode: 'D035' },
  { code: 'B387', nameEn: 'Pipraich', nameHi: 'Pipraich', districtCode: 'D035' },
  { code: 'B388', nameEn: 'Piprauli', nameHi: 'Piprauli', districtCode: 'D035' },
  { code: 'B389', nameEn: 'Sahjanawa', nameHi: 'Sahjanawa', districtCode: 'D035' },
  { code: 'B390', nameEn: 'Sardarnagar', nameHi: 'Sardarnagar', districtCode: 'D035' },
  { code: 'B391', nameEn: 'Uruwa', nameHi: 'Uruwa', districtCode: 'D035' },
  { code: 'B392', nameEn: 'Gohand', nameHi: 'Gohand', districtCode: 'D036' },
  { code: 'B393', nameEn: 'Kurara', nameHi: 'Kurara', districtCode: 'D036' },
  { code: 'B394', nameEn: 'Maudaha', nameHi: 'Maudaha', districtCode: 'D036' },
  { code: 'B395', nameEn: 'Muskara', nameHi: 'Muskara', districtCode: 'D036' },
  { code: 'B396', nameEn: 'Rath', nameHi: 'Rath', districtCode: 'D036' },
  { code: 'B397', nameEn: 'Sarila', nameHi: 'Sarila', districtCode: 'D036' },
  { code: 'B398', nameEn: 'Sumerpur', nameHi: 'Sumerpur', districtCode: 'D036' },
  { code: 'B399', nameEn: 'Dhaulana', nameHi: 'Dhaulana', districtCode: 'D037' },
  { code: 'B400', nameEn: 'Garh Mukteshwar', nameHi: 'Garh Mukteshwar', districtCode: 'D037' },
  { code: 'B401', nameEn: 'Hapur', nameHi: 'Hapur', districtCode: 'D037' },
  { code: 'B402', nameEn: 'Simbhawali', nameHi: 'Simbhawali', districtCode: 'D037' },
  { code: 'B403', nameEn: 'Ahirori', nameHi: 'Ahirori', districtCode: 'D038' },
  { code: 'B404', nameEn: 'Bawan', nameHi: 'Bawan', districtCode: 'D038' },
  { code: 'B405', nameEn: 'Behendar', nameHi: 'Behendar', districtCode: 'D038' },
  { code: 'B406', nameEn: 'Bharawan', nameHi: 'Bharawan', districtCode: 'D038' },
  { code: 'B407', nameEn: 'Bharkhani', nameHi: 'Bharkhani', districtCode: 'D038' },
  { code: 'B408', nameEn: 'Bilgram', nameHi: 'Bilgram', districtCode: 'D038' },
  { code: 'B409', nameEn: 'Hariyawan', nameHi: 'Hariyawan', districtCode: 'D038' },
  { code: 'B410', nameEn: 'Harpalpur', nameHi: 'Harpalpur', districtCode: 'D038' },
  { code: 'B411', nameEn: 'Kachauna', nameHi: 'Kachauna', districtCode: 'D038' },
  { code: 'B412', nameEn: 'Kothawan', nameHi: 'Kothawan', districtCode: 'D038' },
  { code: 'B413', nameEn: 'Madhoganj', nameHi: 'Madhoganj', districtCode: 'D038' },
  { code: 'B414', nameEn: 'Mallawan', nameHi: 'Mallawan', districtCode: 'D038' },
  { code: 'B415', nameEn: 'Pihani', nameHi: 'Pihani', districtCode: 'D038' },
  { code: 'B416', nameEn: 'Sandi', nameHi: 'Sandi', districtCode: 'D038' },
  { code: 'B417', nameEn: 'Sandila', nameHi: 'Sandila', districtCode: 'D038' },
  { code: 'B418', nameEn: 'Shahabad', nameHi: 'Shahabad', districtCode: 'D038' },
  { code: 'B419', nameEn: 'Sursa', nameHi: 'Sursa', districtCode: 'D038' },
  { code: 'B420', nameEn: 'Tandiyawan', nameHi: 'Tandiyawan', districtCode: 'D038' },
  { code: 'B421', nameEn: 'Todarpur', nameHi: 'Todarpur', districtCode: 'D038' },
  { code: 'B422', nameEn: 'Hasayan', nameHi: 'Hasayan', districtCode: 'D039' },
  { code: 'B423', nameEn: 'Hathras', nameHi: 'Hathras', districtCode: 'D039' },
  { code: 'B424', nameEn: 'Mursan', nameHi: 'Mursan', districtCode: 'D039' },
  { code: 'B425', nameEn: 'Sadabad', nameHi: 'Sadabad', districtCode: 'D039' },
  { code: 'B426', nameEn: 'Sasni', nameHi: 'Sasni', districtCode: 'D039' },
  { code: 'B427', nameEn: 'Sehpau', nameHi: 'Sehpau', districtCode: 'D039' },
  { code: 'B428', nameEn: 'Sikandrarao', nameHi: 'Sikandrarao', districtCode: 'D039' },
  { code: 'B429', nameEn: 'Dakore', nameHi: 'Dakore', districtCode: 'D040' },
  { code: 'B430', nameEn: 'Jalaun', nameHi: 'Jalaun', districtCode: 'D040' },
  { code: 'B431', nameEn: 'Kadaura', nameHi: 'Kadaura', districtCode: 'D040' },
  { code: 'B432', nameEn: 'Konch', nameHi: 'Konch', districtCode: 'D040' },
  { code: 'B433', nameEn: 'Kuthaund', nameHi: 'Kuthaund', districtCode: 'D040' },
  { code: 'B434', nameEn: 'Madhogarh', nameHi: 'Madhogarh', districtCode: 'D040' },
  { code: 'B435', nameEn: 'Maheva', nameHi: 'Maheva', districtCode: 'D040' },
  { code: 'B436', nameEn: 'Nadigaon', nameHi: 'Nadigaon', districtCode: 'D040' },
  { code: 'B437', nameEn: 'Rampura', nameHi: 'Rampura', districtCode: 'D040' },
  { code: 'B438', nameEn: 'Badla Pur', nameHi: 'Badla Pur', districtCode: 'D041' },
  { code: 'B439', nameEn: 'Baksha', nameHi: 'Baksha', districtCode: 'D041' },
  { code: 'B440', nameEn: 'Barasathi', nameHi: 'Barasathi', districtCode: 'D041' },
  { code: 'B441', nameEn: 'Dharma Pur', nameHi: 'Dharma Pur', districtCode: 'D041' },
  { code: 'B442', nameEn: 'Dobhi', nameHi: 'Dobhi', districtCode: 'D041' },
  { code: 'B443', nameEn: 'Jalal Pur', nameHi: 'Jalal Pur', districtCode: 'D041' },
  { code: 'B444', nameEn: 'Karanja Kala', nameHi: 'Karanja Kala', districtCode: 'D041' },
  { code: 'B445', nameEn: 'Kerakat', nameHi: 'Kerakat', districtCode: 'D041' },
  { code: 'B446', nameEn: 'Khuthan', nameHi: 'Khuthan', districtCode: 'D041' },
  { code: 'B447', nameEn: 'Machchali Shahar', nameHi: 'Machchali Shahar', districtCode: 'D041' },
  { code: 'B448', nameEn: 'Maharaj Ganj', nameHi: 'Maharaj Ganj', districtCode: 'D041' },
  { code: 'B449', nameEn: 'Mariyahu', nameHi: 'Mariyahu', districtCode: 'D041' },
  { code: 'B450', nameEn: 'Mufti Ganj', nameHi: 'Mufti Ganj', districtCode: 'D041' },
  { code: 'B451', nameEn: 'Mungra Badshah Pur', nameHi: 'Mungra Badshah Pur', districtCode: 'D041' },
  { code: 'B452', nameEn: 'Ram Nagar', nameHi: 'Ram Nagar', districtCode: 'D041' },
  { code: 'B453', nameEn: 'Ram Pur', nameHi: 'Ram Pur', districtCode: 'D041' },
  { code: 'B454', nameEn: 'Shah Ganj', nameHi: 'Shah Ganj', districtCode: 'D041' },
  { code: 'B455', nameEn: 'Sikrara', nameHi: 'Sikrara', districtCode: 'D041' },
  { code: 'B456', nameEn: 'Sirkoni', nameHi: 'Sirkoni', districtCode: 'D041' },
  { code: 'B457', nameEn: 'Suitha Kala', nameHi: 'Suitha Kala', districtCode: 'D041' },
  { code: 'B458', nameEn: 'Sujan Ganj', nameHi: 'Sujan Ganj', districtCode: 'D041' },
  { code: 'B459', nameEn: 'Babina', nameHi: 'Babina', districtCode: 'D042' },
  { code: 'B460', nameEn: 'Badagaon', nameHi: 'Badagaon', districtCode: 'D042' },
  { code: 'B461', nameEn: 'Bamaur', nameHi: 'Bamaur', districtCode: 'D042' },
  { code: 'B462', nameEn: 'Bangra', nameHi: 'Bangra', districtCode: 'D042' },
  { code: 'B463', nameEn: 'Chirgaon', nameHi: 'Chirgaon', districtCode: 'D042' },
  { code: 'B464', nameEn: 'Gursarai', nameHi: 'Gursarai', districtCode: 'D042' },
  { code: 'B465', nameEn: 'Mauranipur', nameHi: 'Mauranipur', districtCode: 'D042' },
  { code: 'B466', nameEn: 'Moth', nameHi: 'Moth', districtCode: 'D042' },
  { code: 'B467', nameEn: 'Chhibramau', nameHi: 'Chhibramau', districtCode: 'D043' },
  { code: 'B468', nameEn: 'Gughrapur', nameHi: 'Gughrapur', districtCode: 'D043' },
  { code: 'B469', nameEn: 'Haseran', nameHi: 'Haseran', districtCode: 'D043' },
  { code: 'B470', nameEn: 'Jalalabad', nameHi: 'Jalalabad', districtCode: 'D043' },
  { code: 'B471', nameEn: 'Kannauj', nameHi: 'Kannauj', districtCode: 'D043' },
  { code: 'B472', nameEn: 'Saurikh', nameHi: 'Saurikh', districtCode: 'D043' },
  { code: 'B473', nameEn: 'Talgram', nameHi: 'Talgram', districtCode: 'D043' },
  { code: 'B474', nameEn: 'Umarda', nameHi: 'Umarda', districtCode: 'D043' },
  { code: 'B475', nameEn: 'Akbarpur', nameHi: 'Akbarpur', districtCode: 'D044' },
  { code: 'B476', nameEn: 'Amrodha', nameHi: 'Amrodha', districtCode: 'D044' },
  { code: 'B477', nameEn: 'Derapur', nameHi: 'Derapur', districtCode: 'D044' },
  { code: 'B478', nameEn: 'Jhinjhak', nameHi: 'Jhinjhak', districtCode: 'D044' },
  { code: 'B479', nameEn: 'Maitha', nameHi: 'Maitha', districtCode: 'D044' },
  { code: 'B480', nameEn: 'Malasa', nameHi: 'Malasa', districtCode: 'D044' },
  { code: 'B481', nameEn: 'Rajpur', nameHi: 'Rajpur', districtCode: 'D044' },
  { code: 'B482', nameEn: 'Rasulabad', nameHi: 'Rasulabad', districtCode: 'D044' },
  { code: 'B483', nameEn: 'Sandalpur', nameHi: 'Sandalpur', districtCode: 'D044' },
  { code: 'B484', nameEn: 'Sarbankhera', nameHi: 'Sarbankhera', districtCode: 'D044' },
  { code: 'B485', nameEn: 'Bhitargaon', nameHi: 'Bhitargaon', districtCode: 'D045' },
  { code: 'B486', nameEn: 'Bilhaur', nameHi: 'Bilhaur', districtCode: 'D045' },
  { code: 'B487', nameEn: 'Chaubeypur', nameHi: 'Chaubeypur', districtCode: 'D045' },
  { code: 'B488', nameEn: 'Ghatampur', nameHi: 'Ghatampur', districtCode: 'D045' },
  { code: 'B489', nameEn: 'Kakwan', nameHi: 'Kakwan', districtCode: 'D045' },
  { code: 'B490', nameEn: 'Kalyanpur', nameHi: 'Kalyanpur', districtCode: 'D045' },
  { code: 'B491', nameEn: 'Patara', nameHi: 'Patara', districtCode: 'D045' },
  { code: 'B492', nameEn: 'Sarsol', nameHi: 'Sarsol', districtCode: 'D045' },
  { code: 'B493', nameEn: 'Shivrajpur', nameHi: 'Shivrajpur', districtCode: 'D045' },
  { code: 'B494', nameEn: 'Vidhunu', nameHi: 'Vidhunu', districtCode: 'D045' },
  { code: 'B495', nameEn: 'Amanpur', nameHi: 'Amanpur', districtCode: 'D046' },
  { code: 'B496', nameEn: 'Ganj Dundwara', nameHi: 'Ganj Dundwara', districtCode: 'D046' },
  { code: 'B497', nameEn: 'Kasganj', nameHi: 'Kasganj', districtCode: 'D046' },
  { code: 'B498', nameEn: 'Patiyali', nameHi: 'Patiyali', districtCode: 'D046' },
  { code: 'B499', nameEn: 'Sahawar', nameHi: 'Sahawar', districtCode: 'D046' },
  { code: 'B500', nameEn: 'Sidhpura', nameHi: 'Sidhpura', districtCode: 'D046' },
  { code: 'B501', nameEn: 'Soron', nameHi: 'Soron', districtCode: 'D046' },
  { code: 'B502', nameEn: 'Chail', nameHi: 'Chail', districtCode: 'D047' },
  { code: 'B503', nameEn: 'Kara', nameHi: 'Kara', districtCode: 'D047' },
  { code: 'B504', nameEn: 'Kaushambi', nameHi: 'Kaushambi', districtCode: 'D047' },
  { code: 'B505', nameEn: 'Manjhanpur', nameHi: 'Manjhanpur', districtCode: 'D047' },
  { code: 'B506', nameEn: 'Mooratganj', nameHi: 'Mooratganj', districtCode: 'D047' },
  { code: 'B507', nameEn: 'Nevada', nameHi: 'Nevada', districtCode: 'D047' },
  { code: 'B508', nameEn: 'Sarsawan', nameHi: 'Sarsawan', districtCode: 'D047' },
  { code: 'B509', nameEn: 'Sirathu', nameHi: 'Sirathu', districtCode: 'D047' },
  { code: 'B510', nameEn: 'Bankeyganj', nameHi: 'Bankeyganj', districtCode: 'D048' },
  { code: 'B511', nameEn: 'Behjam', nameHi: 'Behjam', districtCode: 'D048' },
  { code: 'B512', nameEn: 'Bijuwa', nameHi: 'Bijuwa', districtCode: 'D048' },
  { code: 'B513', nameEn: 'Dhaurhara', nameHi: 'Dhaurhara', districtCode: 'D048' },
  { code: 'B514', nameEn: 'Isanagar', nameHi: 'Isanagar', districtCode: 'D048' },
  { code: 'B515', nameEn: 'Kumbhigola', nameHi: 'Kumbhigola', districtCode: 'D048' },
  { code: 'B516', nameEn: 'Lakhimpur', nameHi: 'Lakhimpur', districtCode: 'D048' },
  { code: 'B517', nameEn: 'Mitauli', nameHi: 'Mitauli', districtCode: 'D048' },
  { code: 'B518', nameEn: 'Mohammadi', nameHi: 'Mohammadi', districtCode: 'D048' },
  { code: 'B519', nameEn: 'Nakaha', nameHi: 'Nakaha', districtCode: 'D048' },
  { code: 'B520', nameEn: 'Nighasan', nameHi: 'Nighasan', districtCode: 'D048' },
  { code: 'B521', nameEn: 'Palia', nameHi: 'Palia', districtCode: 'D048' },
  { code: 'B522', nameEn: 'Pasgawan', nameHi: 'Pasgawan', districtCode: 'D048' },
  { code: 'B523', nameEn: 'Phoolbehar', nameHi: 'Phoolbehar', districtCode: 'D048' },
  { code: 'B524', nameEn: 'Ramia Behar', nameHi: 'Ramia Behar', districtCode: 'D048' },
  { code: 'B525', nameEn: 'Dudhahi', nameHi: 'Dudhahi', districtCode: 'D049' },
  { code: 'B526', nameEn: 'Fazilnagar', nameHi: 'Fazilnagar', districtCode: 'D049' },
  { code: 'B527', nameEn: 'Hata', nameHi: 'Hata', districtCode: 'D049' },
  { code: 'B528', nameEn: 'Kaptainganj', nameHi: 'Kaptainganj', districtCode: 'D049' },
  { code: 'B529', nameEn: 'Kasaya', nameHi: 'Kasaya', districtCode: 'D049' },
  { code: 'B530', nameEn: 'Khadda', nameHi: 'Khadda', districtCode: 'D049' },
  { code: 'B531', nameEn: 'Motichak', nameHi: 'Motichak', districtCode: 'D049' },
  { code: 'B532', nameEn: 'Nebua Naurangia', nameHi: 'Nebua Naurangia', districtCode: 'D049' },
  { code: 'B533', nameEn: 'Padrauna', nameHi: 'Padrauna', districtCode: 'D049' },
  { code: 'B534', nameEn: 'Ramkola', nameHi: 'Ramkola', districtCode: 'D049' },
  { code: 'B535', nameEn: 'Seorahi', nameHi: 'Seorahi', districtCode: 'D049' },
  { code: 'B536', nameEn: 'Sukrauli', nameHi: 'Sukrauli', districtCode: 'D049' },
  { code: 'B537', nameEn: 'Tamkuhiraj', nameHi: 'Tamkuhiraj', districtCode: 'D049' },
  { code: 'B538', nameEn: 'Vishunpura', nameHi: 'Vishunpura', districtCode: 'D049' },
  { code: 'B539', nameEn: 'Bar', nameHi: 'Bar', districtCode: 'D050' },
  { code: 'B540', nameEn: 'Birdha', nameHi: 'Birdha', districtCode: 'D050' },
  { code: 'B541', nameEn: 'Jakhaura', nameHi: 'Jakhaura', districtCode: 'D050' },
  { code: 'B542', nameEn: 'Mandawara', nameHi: 'Mandawara', districtCode: 'D050' },
  { code: 'B543', nameEn: 'Mehroni', nameHi: 'Mehroni', districtCode: 'D050' },
  { code: 'B544', nameEn: 'Talbehat', nameHi: 'Talbehat', districtCode: 'D050' },
  { code: 'B545', nameEn: 'Charkhari', nameHi: 'Charkhari', districtCode: 'D051' },
  { code: 'B546', nameEn: 'Jaitpur', nameHi: 'Jaitpur', districtCode: 'D051' },
  { code: 'B547', nameEn: 'Kabrai', nameHi: 'Kabrai', districtCode: 'D051' },
  { code: 'B548', nameEn: 'Panwari', nameHi: 'Panwari', districtCode: 'D051' },
  { code: 'B549', nameEn: 'Bridgemanganj', nameHi: 'Bridgemanganj', districtCode: 'D052' },
  { code: 'B550', nameEn: 'Dhani', nameHi: 'Dhani', districtCode: 'D052' },
  { code: 'B551', nameEn: 'Ghughli', nameHi: 'Ghughli', districtCode: 'D052' },
  { code: 'B552', nameEn: 'Lakshmipur', nameHi: 'Lakshmipur', districtCode: 'D052' },
  { code: 'B553', nameEn: 'Mahrajganj', nameHi: 'Mahrajganj', districtCode: 'D052' },
  { code: 'B554', nameEn: 'Mithaura', nameHi: 'Mithaura', districtCode: 'D052' },
  { code: 'B555', nameEn: 'Nautanwa', nameHi: 'Nautanwa', districtCode: 'D052' },
  { code: 'B556', nameEn: 'Nichlaul', nameHi: 'Nichlaul', districtCode: 'D052' },
  { code: 'B557', nameEn: 'Paniyara', nameHi: 'Paniyara', districtCode: 'D052' },
  { code: 'B558', nameEn: 'Partawal', nameHi: 'Partawal', districtCode: 'D052' },
  { code: 'B559', nameEn: 'Pharenda', nameHi: 'Pharenda', districtCode: 'D052' },
  { code: 'B560', nameEn: 'Siswa', nameHi: 'Siswa', districtCode: 'D052' },
  { code: 'B561', nameEn: 'Barnahal', nameHi: 'Barnahal', districtCode: 'D053' },
  { code: 'B562', nameEn: 'Bewar', nameHi: 'Bewar', districtCode: 'D053' },
  { code: 'B563', nameEn: 'Ghiror', nameHi: 'Ghiror', districtCode: 'D053' },
  { code: 'B564', nameEn: 'Jageer', nameHi: 'Jageer', districtCode: 'D053' },
  { code: 'B565', nameEn: 'Karhal', nameHi: 'Karhal', districtCode: 'D053' },
  { code: 'B566', nameEn: 'Kishni', nameHi: 'Kishni', districtCode: 'D053' },
  { code: 'B567', nameEn: 'Kuraoli', nameHi: 'Kuraoli', districtCode: 'D053' },
  { code: 'B568', nameEn: 'Mainpuri', nameHi: 'Mainpuri', districtCode: 'D053' },
  { code: 'B569', nameEn: 'Sultanganj', nameHi: 'Sultanganj', districtCode: 'D053' },
  { code: 'B570', nameEn: 'Baldeo', nameHi: 'Baldeo', districtCode: 'D054' },
  { code: 'B571', nameEn: 'Chaumuha', nameHi: 'Chaumuha', districtCode: 'D054' },
  { code: 'B572', nameEn: 'Chhata', nameHi: 'Chhata', districtCode: 'D054' },
  { code: 'B573', nameEn: 'Farah', nameHi: 'Farah', districtCode: 'D054' },
  { code: 'B574', nameEn: 'Govardhan', nameHi: 'Govardhan', districtCode: 'D054' },
  { code: 'B575', nameEn: 'Mat', nameHi: 'Mat', districtCode: 'D054' },
  { code: 'B576', nameEn: 'Mathura', nameHi: 'Mathura', districtCode: 'D054' },
  { code: 'B577', nameEn: 'Nandgaon', nameHi: 'Nandgaon', districtCode: 'D054' },
  { code: 'B578', nameEn: 'Nohjhil', nameHi: 'Nohjhil', districtCode: 'D054' },
  { code: 'B579', nameEn: 'Raya', nameHi: 'Raya', districtCode: 'D054' },
  { code: 'B580', nameEn: 'Badraon', nameHi: 'Badraon', districtCode: 'D055' },
  { code: 'B581', nameEn: 'Dohri Ghat', nameHi: 'Dohri Ghat', districtCode: 'D055' },
  { code: 'B582', nameEn: 'Fatehpur Madaun', nameHi: 'Fatehpur Madaun', districtCode: 'D055' },
  { code: 'B583', nameEn: 'Ghosi', nameHi: 'Ghosi', districtCode: 'D055' },
  { code: 'B584', nameEn: 'Kopaganj', nameHi: 'Kopaganj', districtCode: 'D055' },
  { code: 'B585', nameEn: 'Mohammadabad Gohana', nameHi: 'Mohammadabad Gohana', districtCode: 'D055' },
  { code: 'B586', nameEn: 'Pardaha', nameHi: 'Pardaha', districtCode: 'D055' },
  { code: 'B587', nameEn: 'Ranipur', nameHi: 'Ranipur', districtCode: 'D055' },
  { code: 'B588', nameEn: 'Ratanpura', nameHi: 'Ratanpura', districtCode: 'D055' },
  { code: 'B589', nameEn: 'Daurala', nameHi: 'Daurala', districtCode: 'D056' },
  { code: 'B590', nameEn: 'Hastinapur', nameHi: 'Hastinapur', districtCode: 'D056' },
  { code: 'B591', nameEn: 'Janikhurd', nameHi: 'Janikhurd', districtCode: 'D056' },
  { code: 'B592', nameEn: 'Kharkhoda', nameHi: 'Kharkhoda', districtCode: 'D056' },
  { code: 'B593', nameEn: 'Machra', nameHi: 'Machra', districtCode: 'D056' },
  { code: 'B594', nameEn: 'Mawana Kalan', nameHi: 'Mawana Kalan', districtCode: 'D056' },
  { code: 'B595', nameEn: 'Meerut', nameHi: 'Meerut', districtCode: 'D056' },
  { code: 'B596', nameEn: 'Parikshitgarh', nameHi: 'Parikshitgarh', districtCode: 'D056' },
  { code: 'B597', nameEn: 'Rajpura', nameHi: 'Rajpura', districtCode: 'D056' },
  { code: 'B598', nameEn: 'Rohta', nameHi: 'Rohta', districtCode: 'D056' },
  { code: 'B599', nameEn: 'Sardhana', nameHi: 'Sardhana', districtCode: 'D056' },
  { code: 'B600', nameEn: 'Sarurpur Khurd', nameHi: 'Sarurpur Khurd', districtCode: 'D056' },
  { code: 'B601', nameEn: 'Chhanvey', nameHi: 'Chhanvey', districtCode: 'D057' },
  { code: 'B602', nameEn: 'Hallia', nameHi: 'Hallia', districtCode: 'D057' },
  { code: 'B603', nameEn: 'Jamalpur', nameHi: 'Jamalpur', districtCode: 'D057' },
  { code: 'B604', nameEn: 'Kon', nameHi: 'Kon', districtCode: 'D057' },
  { code: 'B605', nameEn: 'Lalganj', nameHi: 'Lalganj', districtCode: 'D057' },
  { code: 'B606', nameEn: 'Majhawa', nameHi: 'Majhawa', districtCode: 'D057' },
  { code: 'B607', nameEn: 'Nagar (City)', nameHi: 'Nagar (City)', districtCode: 'D057' },
  { code: 'B608', nameEn: 'Narainpur', nameHi: 'Narainpur', districtCode: 'D057' },
  { code: 'B609', nameEn: 'Pahari', nameHi: 'Pahari', districtCode: 'D057' },
  { code: 'B610', nameEn: 'Patehra', nameHi: 'Patehra', districtCode: 'D057' },
  { code: 'B611', nameEn: 'Rajgarh', nameHi: 'Rajgarh', districtCode: 'D057' },
  { code: 'B612', nameEn: 'Shikhar', nameHi: 'Shikhar', districtCode: 'D057' },
  { code: 'B613', nameEn: 'Bhagatpur Tanda', nameHi: 'Bhagatpur Tanda', districtCode: 'D058' },
  { code: 'B614', nameEn: 'Bilari', nameHi: 'Bilari', districtCode: 'D058' },
  { code: 'B615', nameEn: 'Chhajlet', nameHi: 'Chhajlet', districtCode: 'D058' },
  { code: 'B616', nameEn: 'Dilari', nameHi: 'Dilari', districtCode: 'D058' },
  { code: 'B617', nameEn: 'Kundarki', nameHi: 'Kundarki', districtCode: 'D058' },
  { code: 'B618', nameEn: 'Moradabad', nameHi: 'Moradabad', districtCode: 'D058' },
  { code: 'B619', nameEn: 'Munda Pandey', nameHi: 'Munda Pandey', districtCode: 'D058' },
  { code: 'B620', nameEn: 'Thakurdwara', nameHi: 'Thakurdwara', districtCode: 'D058' },
  { code: 'B621', nameEn: 'Baghara', nameHi: 'Baghara', districtCode: 'D059' },
  { code: 'B622', nameEn: 'Budhana', nameHi: 'Budhana', districtCode: 'D059' },
  { code: 'B623', nameEn: 'Charthawal', nameHi: 'Charthawal', districtCode: 'D059' },
  { code: 'B624', nameEn: 'Jansath', nameHi: 'Jansath', districtCode: 'D059' },
  { code: 'B625', nameEn: 'Khatauli', nameHi: 'Khatauli', districtCode: 'D059' },
  { code: 'B626', nameEn: 'Morna', nameHi: 'Morna', districtCode: 'D059' },
  { code: 'B627', nameEn: 'Muzaffarnagar', nameHi: 'Muzaffarnagar', districtCode: 'D059' },
  { code: 'B628', nameEn: 'Purkaji', nameHi: 'Purkaji', districtCode: 'D059' },
  { code: 'B629', nameEn: 'Shahpur', nameHi: 'Shahpur', districtCode: 'D059' },
  { code: 'B630', nameEn: 'Amariya', nameHi: 'Amariya', districtCode: 'D060' },
  { code: 'B631', nameEn: 'Barkhera', nameHi: 'Barkhera', districtCode: 'D060' },
  { code: 'B632', nameEn: 'Bilsanda', nameHi: 'Bilsanda', districtCode: 'D060' },
  { code: 'B633', nameEn: 'Bisalpur', nameHi: 'Bisalpur', districtCode: 'D060' },
  { code: 'B634', nameEn: 'Lalaurikhera', nameHi: 'Lalaurikhera', districtCode: 'D060' },
  { code: 'B635', nameEn: 'Marori', nameHi: 'Marori', districtCode: 'D060' },
  { code: 'B636', nameEn: 'Puranpur', nameHi: 'Puranpur', districtCode: 'D060' },
  { code: 'B637', nameEn: 'Aspur Deosara', nameHi: 'Aspur Deosara', districtCode: 'D061' },
  { code: 'B638', nameEn: 'Baba Belkharnath Dham', nameHi: 'Baba Belkharnath Dham', districtCode: 'D061' },
  { code: 'B639', nameEn: 'Babaganj', nameHi: 'Babaganj', districtCode: 'D061' },
  { code: 'B640', nameEn: 'Bihar', nameHi: 'Bihar', districtCode: 'D061' },
  { code: 'B641', nameEn: 'Gaura', nameHi: 'Gaura', districtCode: 'D061' },
  { code: 'B642', nameEn: 'Kalakankar', nameHi: 'Kalakankar', districtCode: 'D061' },
  { code: 'B643', nameEn: 'Kunda', nameHi: 'Kunda', districtCode: 'D061' },
  { code: 'B644', nameEn: 'Lakshamanpur', nameHi: 'Lakshamanpur', districtCode: 'D061' },
  { code: 'B645', nameEn: 'Lalganj', nameHi: 'Lalganj', districtCode: 'D061' },
  { code: 'B646', nameEn: 'Magraura', nameHi: 'Magraura', districtCode: 'D061' },
  { code: 'B647', nameEn: 'Mandhata', nameHi: 'Mandhata', districtCode: 'D061' },
  { code: 'B648', nameEn: 'Patti', nameHi: 'Patti', districtCode: 'D061' },
  { code: 'B649', nameEn: 'Pratapgarh (Sadar)', nameHi: 'Pratapgarh (Sadar)', districtCode: 'D061' },
  { code: 'B650', nameEn: 'Rampur Sanramgarh', nameHi: 'Rampur Sanramgarh', districtCode: 'D061' },
  { code: 'B651', nameEn: 'Sandwa Chandrika', nameHi: 'Sandwa Chandrika', districtCode: 'D061' },
  { code: 'B652', nameEn: 'Sangipur', nameHi: 'Sangipur', districtCode: 'D061' },
  { code: 'B653', nameEn: 'Shivgarh', nameHi: 'Shivgarh', districtCode: 'D061' },
  { code: 'B654', nameEn: 'Bahadurpur', nameHi: 'Bahadurpur', districtCode: 'D062' },
  { code: 'B655', nameEn: 'Bahria', nameHi: 'Bahria', districtCode: 'D062' },
  { code: 'B656', nameEn: 'Bhagwatpur', nameHi: 'Bhagwatpur', districtCode: 'D062' },
  { code: 'B657', nameEn: 'Chaka', nameHi: 'Chaka', districtCode: 'D062' },
  { code: 'B658', nameEn: 'Dhanupur', nameHi: 'Dhanupur', districtCode: 'D062' },
  { code: 'B659', nameEn: 'Handia', nameHi: 'Handia', districtCode: 'D062' },
  { code: 'B660', nameEn: 'Holagarh', nameHi: 'Holagarh', districtCode: 'D062' },
  { code: 'B661', nameEn: 'Jasra', nameHi: 'Jasra', districtCode: 'D062' },
  { code: 'B662', nameEn: 'Karchhana', nameHi: 'Karchhana', districtCode: 'D062' },
  { code: 'B663', nameEn: 'Kaudhiyara', nameHi: 'Kaudhiyara', districtCode: 'D062' },
  { code: 'B664', nameEn: 'Kaurihar', nameHi: 'Kaurihar', districtCode: 'D062' },
  { code: 'B665', nameEn: 'Koraon', nameHi: 'Koraon', districtCode: 'D062' },
  { code: 'B666', nameEn: 'Manda', nameHi: 'Manda', districtCode: 'D062' },
  { code: 'B667', nameEn: 'Mauaima', nameHi: 'Mauaima', districtCode: 'D062' },
  { code: 'B668', nameEn: 'Meja', nameHi: 'Meja', districtCode: 'D062' },
  { code: 'B669', nameEn: 'Phulpur', nameHi: 'Phulpur', districtCode: 'D062' },
  { code: 'B670', nameEn: 'Pratappur', nameHi: 'Pratappur', districtCode: 'D062' },
  { code: 'B671', nameEn: 'Sahson', nameHi: 'Sahson', districtCode: 'D062' },
  { code: 'B672', nameEn: 'Saidabad', nameHi: 'Saidabad', districtCode: 'D062' },
  { code: 'B673', nameEn: 'Shankargarh', nameHi: 'Shankargarh', districtCode: 'D062' },
  { code: 'B674', nameEn: 'Soraon', nameHi: 'Soraon', districtCode: 'D062' },
  { code: 'B675', nameEn: 'Sringverpur Dham', nameHi: 'Sringverpur Dham', districtCode: 'D062' },
  { code: 'B676', nameEn: 'Uruwan', nameHi: 'Uruwan', districtCode: 'D062' },
  { code: 'B677', nameEn: 'Amawan', nameHi: 'Amawan', districtCode: 'D063' },
  { code: 'B678', nameEn: 'Bachharawan', nameHi: 'Bachharawan', districtCode: 'D063' },
  { code: 'B679', nameEn: 'Chhatoh', nameHi: 'Chhatoh', districtCode: 'D063' },
  { code: 'B680', nameEn: 'Dalmau', nameHi: 'Dalmau', districtCode: 'D063' },
  { code: 'B681', nameEn: 'Deenshah Gaura', nameHi: 'Deenshah Gaura', districtCode: 'D063' },
  { code: 'B682', nameEn: 'Dih', nameHi: 'Dih', districtCode: 'D063' },
  { code: 'B683', nameEn: 'Harchandpur', nameHi: 'Harchandpur', districtCode: 'D063' },
  { code: 'B684', nameEn: 'Jagatpur', nameHi: 'Jagatpur', districtCode: 'D063' },
  { code: 'B685', nameEn: 'Khiron', nameHi: 'Khiron', districtCode: 'D063' },
  { code: 'B686', nameEn: 'Lalganj', nameHi: 'Lalganj', districtCode: 'D063' },
  { code: 'B687', nameEn: 'Mahrajganj', nameHi: 'Mahrajganj', districtCode: 'D063' },
  { code: 'B688', nameEn: 'Rahi', nameHi: 'Rahi', districtCode: 'D063' },
  { code: 'B689', nameEn: 'Rohania', nameHi: 'Rohania', districtCode: 'D063' },
  { code: 'B690', nameEn: 'Salon', nameHi: 'Salon', districtCode: 'D063' },
  { code: 'B691', nameEn: 'Sareni', nameHi: 'Sareni', districtCode: 'D063' },
  { code: 'B692', nameEn: 'Sataon', nameHi: 'Sataon', districtCode: 'D063' },
  { code: 'B693', nameEn: 'Shivgarh', nameHi: 'Shivgarh', districtCode: 'D063' },
  { code: 'B694', nameEn: 'Unchahar', nameHi: 'Unchahar', districtCode: 'D063' },
  { code: 'B695', nameEn: 'Bilaspur', nameHi: 'Bilaspur', districtCode: 'D064' },
  { code: 'B696', nameEn: 'Chamraon', nameHi: 'Chamraon', districtCode: 'D064' },
  { code: 'B697', nameEn: 'Milak', nameHi: 'Milak', districtCode: 'D064' },
  { code: 'B698', nameEn: 'Saidnagar', nameHi: 'Saidnagar', districtCode: 'D064' },
  { code: 'B699', nameEn: 'Shahabad', nameHi: 'Shahabad', districtCode: 'D064' },
  { code: 'B700', nameEn: 'Suar', nameHi: 'Suar', districtCode: 'D064' },
  { code: 'B701', nameEn: 'Ballia Kheri', nameHi: 'Ballia Kheri', districtCode: 'D065' },
  { code: 'B702', nameEn: 'Deoband', nameHi: 'Deoband', districtCode: 'D065' },
  { code: 'B703', nameEn: 'Gangoh', nameHi: 'Gangoh', districtCode: 'D065' },
  { code: 'B704', nameEn: 'Muzaffarabad', nameHi: 'Muzaffarabad', districtCode: 'D065' },
  { code: 'B705', nameEn: 'Nagal', nameHi: 'Nagal', districtCode: 'D065' },
  { code: 'B706', nameEn: 'Nakur', nameHi: 'Nakur', districtCode: 'D065' },
  { code: 'B707', nameEn: 'Nanauta', nameHi: 'Nanauta', districtCode: 'D065' },
  { code: 'B708', nameEn: 'Puwarka', nameHi: 'Puwarka', districtCode: 'D065' },
  { code: 'B709', nameEn: 'Rampur Maniharan', nameHi: 'Rampur Maniharan', districtCode: 'D065' },
  { code: 'B710', nameEn: 'Sadauli Qadeem', nameHi: 'Sadauli Qadeem', districtCode: 'D065' },
  { code: 'B711', nameEn: 'Sarsawan', nameHi: 'Sarsawan', districtCode: 'D065' },
  { code: 'B712', nameEn: 'Asmauli', nameHi: 'Asmauli', districtCode: 'D066' },
  { code: 'B713', nameEn: 'Bahjoi', nameHi: 'Bahjoi', districtCode: 'D066' },
  { code: 'B714', nameEn: 'Baniyakhera', nameHi: 'Baniyakhera', districtCode: 'D066' },
  { code: 'B715', nameEn: 'Gunnaur', nameHi: 'Gunnaur', districtCode: 'D066' },
  { code: 'B716', nameEn: 'Junawai', nameHi: 'Junawai', districtCode: 'D066' },
  { code: 'B717', nameEn: 'Panwasa', nameHi: 'Panwasa', districtCode: 'D066' },
  { code: 'B718', nameEn: 'Rajpura', nameHi: 'Rajpura', districtCode: 'D066' },
  { code: 'B719', nameEn: 'Sambhal', nameHi: 'Sambhal', districtCode: 'D066' },
  { code: 'B720', nameEn: 'Baghauli', nameHi: 'Baghauli', districtCode: 'D067' },
  { code: 'B721', nameEn: 'Belhar Kala', nameHi: 'Belhar Kala', districtCode: 'D067' },
  { code: 'B722', nameEn: 'Hainsar Bazar', nameHi: 'Hainsar Bazar', districtCode: 'D067' },
  { code: 'B723', nameEn: 'Khalilabad', nameHi: 'Khalilabad', districtCode: 'D067' },
  { code: 'B724', nameEn: 'Mehdawal', nameHi: 'Mehdawal', districtCode: 'D067' },
  { code: 'B725', nameEn: 'Nath Nagar', nameHi: 'Nath Nagar', districtCode: 'D067' },
  { code: 'B726', nameEn: 'Pauli', nameHi: 'Pauli', districtCode: 'D067' },
  { code: 'B727', nameEn: 'Santha', nameHi: 'Santha', districtCode: 'D067' },
  { code: 'B728', nameEn: 'Semariyawan', nameHi: 'Semariyawan', districtCode: 'D067' },
  { code: 'B729', nameEn: 'Banda', nameHi: 'Banda', districtCode: 'D068' },
  { code: 'B730', nameEn: 'Bhawal Khera', nameHi: 'Bhawal Khera', districtCode: 'D068' },
  { code: 'B731', nameEn: 'Dadrol', nameHi: 'Dadrol', districtCode: 'D068' },
  { code: 'B732', nameEn: 'Jaitipur', nameHi: 'Jaitipur', districtCode: 'D068' },
  { code: 'B733', nameEn: 'Jalalabad', nameHi: 'Jalalabad', districtCode: 'D068' },
  { code: 'B734', nameEn: 'Kalan', nameHi: 'Kalan', districtCode: 'D068' },
  { code: 'B735', nameEn: 'Kanth', nameHi: 'Kanth', districtCode: 'D068' },
  { code: 'B736', nameEn: 'Khudaganj Katra', nameHi: 'Khudaganj Katra', districtCode: 'D068' },
  { code: 'B737', nameEn: 'Khutar', nameHi: 'Khutar', districtCode: 'D068' },
  { code: 'B738', nameEn: 'Madnapur', nameHi: 'Madnapur', districtCode: 'D068' },
  { code: 'B739', nameEn: 'Mirzapur', nameHi: 'Mirzapur', districtCode: 'D068' },
  { code: 'B740', nameEn: 'Nigohi', nameHi: 'Nigohi', districtCode: 'D068' },
  { code: 'B741', nameEn: 'Powayan', nameHi: 'Powayan', districtCode: 'D068' },
  { code: 'B742', nameEn: 'Sindhauli', nameHi: 'Sindhauli', districtCode: 'D068' },
  { code: 'B743', nameEn: 'Tilhar', nameHi: 'Tilhar', districtCode: 'D068' },
  { code: 'B744', nameEn: 'Kairana', nameHi: 'Kairana', districtCode: 'D069' },
  { code: 'B745', nameEn: 'Kandhla', nameHi: 'Kandhla', districtCode: 'D069' },
  { code: 'B746', nameEn: 'Shamli', nameHi: 'Shamli', districtCode: 'D069' },
  { code: 'B747', nameEn: 'Thana Bhawan', nameHi: 'Thana Bhawan', districtCode: 'D069' },
  { code: 'B748', nameEn: 'Un', nameHi: 'Un', districtCode: 'D069' },
  { code: 'B749', nameEn: 'Ekona', nameHi: 'Ekona', districtCode: 'D070' },
  { code: 'B750', nameEn: 'Gilaula', nameHi: 'Gilaula', districtCode: 'D070' },
  { code: 'B751', nameEn: 'Hariharpur Rani', nameHi: 'Hariharpur Rani', districtCode: 'D070' },
  { code: 'B752', nameEn: 'Jamunaha', nameHi: 'Jamunaha', districtCode: 'D070' },
  { code: 'B753', nameEn: 'Sirsiya', nameHi: 'Sirsiya', districtCode: 'D070' },
  { code: 'B754', nameEn: 'Bansi', nameHi: 'Bansi', districtCode: 'D071' },
  { code: 'B755', nameEn: 'Barhni', nameHi: 'Barhni', districtCode: 'D071' },
  { code: 'B756', nameEn: 'Bhanwapur', nameHi: 'Bhanwapur', districtCode: 'D071' },
  { code: 'B757', nameEn: 'Birdpur', nameHi: 'Birdpur', districtCode: 'D071' },
  { code: 'B758', nameEn: 'Domariyaganj', nameHi: 'Domariyaganj', districtCode: 'D071' },
  { code: 'B759', nameEn: 'Itwa', nameHi: 'Itwa', districtCode: 'D071' },
  { code: 'B760', nameEn: 'Jogia', nameHi: 'Jogia', districtCode: 'D071' },
  { code: 'B761', nameEn: 'Khesraha', nameHi: 'Khesraha', districtCode: 'D071' },
  { code: 'B762', nameEn: 'Khuniyaon', nameHi: 'Khuniyaon', districtCode: 'D071' },
  { code: 'B763', nameEn: 'Lotan', nameHi: 'Lotan', districtCode: 'D071' },
  { code: 'B764', nameEn: 'Mithwal', nameHi: 'Mithwal', districtCode: 'D071' },
  { code: 'B765', nameEn: 'Naugarh', nameHi: 'Naugarh', districtCode: 'D071' },
  { code: 'B766', nameEn: 'Shoharatgarh', nameHi: 'Shoharatgarh', districtCode: 'D071' },
  { code: 'B767', nameEn: 'Uska Bazar', nameHi: 'Uska Bazar', districtCode: 'D071' },
  { code: 'B768', nameEn: 'Ailiya', nameHi: 'Ailiya', districtCode: 'D072' },
  { code: 'B769', nameEn: 'Behta', nameHi: 'Behta', districtCode: 'D072' },
  { code: 'B770', nameEn: 'Biswan', nameHi: 'Biswan', districtCode: 'D072' },
  { code: 'B771', nameEn: 'Gondlamau', nameHi: 'Gondlamau', districtCode: 'D072' },
  { code: 'B772', nameEn: 'Hargaon', nameHi: 'Hargaon', districtCode: 'D072' },
  { code: 'B773', nameEn: 'Kasmanda', nameHi: 'Kasmanda', districtCode: 'D072' },
  { code: 'B774', nameEn: 'Khairabad', nameHi: 'Khairabad', districtCode: 'D072' },
  { code: 'B775', nameEn: 'Laharpur', nameHi: 'Laharpur', districtCode: 'D072' },
  { code: 'B776', nameEn: 'Machhrehta', nameHi: 'Machhrehta', districtCode: 'D072' },
  { code: 'B777', nameEn: 'Mahmudabad', nameHi: 'Mahmudabad', districtCode: 'D072' },
  { code: 'B778', nameEn: 'Maholi', nameHi: 'Maholi', districtCode: 'D072' },
  { code: 'B779', nameEn: 'Misrikh', nameHi: 'Misrikh', districtCode: 'D072' },
  { code: 'B780', nameEn: 'Pahala', nameHi: 'Pahala', districtCode: 'D072' },
  { code: 'B781', nameEn: 'Parsendi', nameHi: 'Parsendi', districtCode: 'D072' },
  { code: 'B782', nameEn: 'Pisawan', nameHi: 'Pisawan', districtCode: 'D072' },
  { code: 'B783', nameEn: 'Rampur Mathura', nameHi: 'Rampur Mathura', districtCode: 'D072' },
  { code: 'B784', nameEn: 'Reusa', nameHi: 'Reusa', districtCode: 'D072' },
  { code: 'B785', nameEn: 'Sakran', nameHi: 'Sakran', districtCode: 'D072' },
  { code: 'B786', nameEn: 'Sidhauli', nameHi: 'Sidhauli', districtCode: 'D072' },
  { code: 'B787', nameEn: 'Babhani', nameHi: 'Babhani', districtCode: 'D073' },
  { code: 'B788', nameEn: 'Chatra', nameHi: 'Chatra', districtCode: 'D073' },
  { code: 'B789', nameEn: 'Chopan', nameHi: 'Chopan', districtCode: 'D073' },
  { code: 'B790', nameEn: 'Dudhi', nameHi: 'Dudhi', districtCode: 'D073' },
  { code: 'B791', nameEn: 'Ghorawal', nameHi: 'Ghorawal', districtCode: 'D073' },
  { code: 'B792', nameEn: 'Karma', nameHi: 'Karma', districtCode: 'D073' },
  { code: 'B793', nameEn: 'Kone', nameHi: 'Kone', districtCode: 'D073' },
  { code: 'B794', nameEn: 'Myorpur', nameHi: 'Myorpur', districtCode: 'D073' },
  { code: 'B795', nameEn: 'Nagwa', nameHi: 'Nagwa', districtCode: 'D073' },
  { code: 'B796', nameEn: 'Robertsganj', nameHi: 'Robertsganj', districtCode: 'D073' },
  { code: 'B797', nameEn: 'Akhand Nagar', nameHi: 'Akhand Nagar', districtCode: 'D074' },
  { code: 'B798', nameEn: 'Baldirai', nameHi: 'Baldirai', districtCode: 'D074' },
  { code: 'B799', nameEn: 'Bhadaiya', nameHi: 'Bhadaiya', districtCode: 'D074' },
  { code: 'B800', nameEn: 'Dhanpatganj', nameHi: 'Dhanpatganj', districtCode: 'D074' },
  { code: 'B801', nameEn: 'Dostpur', nameHi: 'Dostpur', districtCode: 'D074' },
  { code: 'B802', nameEn: 'Dubepur', nameHi: 'Dubepur', districtCode: 'D074' },
  { code: 'B803', nameEn: 'Jaisinghpur', nameHi: 'Jaisinghpur', districtCode: 'D074' },
  { code: 'B804', nameEn: 'Kadipur', nameHi: 'Kadipur', districtCode: 'D074' },
  { code: 'B805', nameEn: 'Karaudikala', nameHi: 'Karaudikala', districtCode: 'D074' },
  { code: 'B806', nameEn: 'Kurebhar', nameHi: 'Kurebhar', districtCode: 'D074' },
  { code: 'B807', nameEn: 'Kurwar', nameHi: 'Kurwar', districtCode: 'D074' },
  { code: 'B808', nameEn: 'Lambhua', nameHi: 'Lambhua', districtCode: 'D074' },
  { code: 'B809', nameEn: 'Motigarpur', nameHi: 'Motigarpur', districtCode: 'D074' },
  { code: 'B810', nameEn: 'P.P.Kamaicha', nameHi: 'P.P.Kamaicha', districtCode: 'D074' },
  { code: 'B811', nameEn: 'Asoha', nameHi: 'Asoha', districtCode: 'D075' },
  { code: 'B812', nameEn: 'Auras', nameHi: 'Auras', districtCode: 'D075' },
  { code: 'B813', nameEn: 'Bangarmau', nameHi: 'Bangarmau', districtCode: 'D075' },
  { code: 'B814', nameEn: 'Bichhiya', nameHi: 'Bichhiya', districtCode: 'D075' },
  { code: 'B815', nameEn: 'Bighapur', nameHi: 'Bighapur', districtCode: 'D075' },
  { code: 'B816', nameEn: 'Fatehpur Chaurasi', nameHi: 'Fatehpur Chaurasi', districtCode: 'D075' },
  { code: 'B817', nameEn: 'Ganj Moradabad', nameHi: 'Ganj Moradabad', districtCode: 'D075' },
  { code: 'B818', nameEn: 'Hasanganj', nameHi: 'Hasanganj', districtCode: 'D075' },
  { code: 'B819', nameEn: 'Hilauli', nameHi: 'Hilauli', districtCode: 'D075' },
  { code: 'B820', nameEn: 'Mianganj', nameHi: 'Mianganj', districtCode: 'D075' },
  { code: 'B821', nameEn: 'Nawabganj', nameHi: 'Nawabganj', districtCode: 'D075' },
  { code: 'B822', nameEn: 'Purwa', nameHi: 'Purwa', districtCode: 'D075' },
  { code: 'B823', nameEn: 'Safipur', nameHi: 'Safipur', districtCode: 'D075' },
  { code: 'B824', nameEn: 'Sikandarpur Karan', nameHi: 'Sikandarpur Karan', districtCode: 'D075' },
  { code: 'B825', nameEn: 'Sikandarpur Sarausi', nameHi: 'Sikandarpur Sarausi', districtCode: 'D075' },
  { code: 'B826', nameEn: 'Sumerpur', nameHi: 'Sumerpur', districtCode: 'D075' },
];
