import { prisma } from '@/lib/db';

/**
 * The School Improvement Plan, derived rather than stored.
 *
 * The source flowchart is specific: "A customized School Improvement Plan is shared with the
 * school based on its self-reported score. If the school's rating or any parameter level
 * changes, the Plan updates automatically."
 *
 * The obvious build is a Plan table regenerated by a hook on every response change. This
 * computes it on read instead, and that is the whole design decision. A stored plan has to be
 * invalidated, and every path that changes a level has to remember to do it: the school's own
 * form, a verifier's correction, an appeal decision, a supervisor's revision, a backfill. Miss
 * one and a school is following a plan for a level it no longer holds, which is worse than no
 * plan at all. Derived on read, "updates automatically" is true by construction rather than by
 * discipline.
 *
 * The actions are not invented either. Where a school sits below the top level, the action is
 * the framework's own text for the next level up, verbatim from the SCERT checklist. Nobody
 * has to write improvement advice, and the school reads the same words the assessment will be
 * judged against.
 */

/**
 * Which level a school should aim at next, given the options and the one it picked.
 *
 * Extracted and tested because it is an off-by-one that would be wrong on every school's plan
 * at once. Two ways to get it wrong: offering a level above the top, and offering the top to a
 * school already there. Both produce an action nobody can take.
 */
export function nextLevelIndex(optionCount: number, currentIndex: number): number | null {
  if (currentIndex < 0 || currentIndex >= optionCount) return null;
  // Already at the best available level. No action, rather than an action to a level the
  // framework does not define.
  if (currentIndex >= optionCount - 1) return null;
  // One step, not a leap to the top. A school on level 1 asked to reach level 3 within a year
  // will do neither; the next level is the thing it can actually plan for.
  return currentIndex + 1;
}

export type PlanAction = {
  parameterCode: string;
  parameterTitleEn: string;
  parameterTitleHi: string;
  currentLevel: number;
  targetLevel: number;
  /** The framework's description of the next level up. This is the action. */
  targetDescriptionEn: string;
  targetDescriptionHi: string;
};

export type PlanDomain = {
  code: string;
  titleEn: string;
  titleHi: string;
  weightPercent: number | null;
  /** Ordered worst-first within the domain, so the biggest gaps are read first. */
  actions: PlanAction[];
  /** Indicators in this domain already at the top level. Counted, not listed. */
  atTopLevel: number;
};

export type ImprovementPlan = {
  schoolUdise: string;
  cycleName: string;
  /** Answered indicators, and how many of them are already at the top level. */
  answered: number;
  atTopLevel: number;
  /** Domains carrying at least one action, ordered by weight then by number of actions. */
  domains: PlanDomain[];
  /** True when the school has answered nothing yet, so the page can say why it is empty. */
  notStarted: boolean;
};

export async function buildImprovementPlan(
  schoolUdise: string,
): Promise<ImprovementPlan | null> {
  const cycle = await prisma.cycle.findFirst({
    where: { isActive: true },
    select: { id: true, name: true },
  });
  if (!cycle) return null;

  const submission = await prisma.selfAssessmentSubmission.findUnique({
    where: { cycleId_schoolUdise: { cycleId: cycle.id, schoolUdise } },
    include: {
      responses: {
        include: {
          parameter: {
            include: {
              options: { orderBy: { order: 'asc' } },
              subDomain: { include: { domain: true } },
            },
          },
        },
      },
    },
  });

  if (!submission || submission.responses.length === 0) {
    return {
      schoolUdise,
      cycleName: cycle.name,
      answered: 0,
      atTopLevel: 0,
      domains: [],
      notStarted: true,
    };
  }

  const byDomain = new Map<string, PlanDomain>();
  let answered = 0;
  let atTopLevel = 0;

  for (const response of submission.responses) {
    const param = response.parameter;
    const options = param.options;
    if (options.length === 0) continue;

    const currentIndex = options.findIndex((o) => o.key === response.selectedOptionKey);
    if (currentIndex === -1) continue;

    answered += 1;
    const domain = param.subDomain.domain;

    let entry = byDomain.get(domain.code);
    if (!entry) {
      entry = {
        code: domain.code,
        titleEn: domain.titleEn,
        titleHi: domain.titleHi,
        weightPercent: domain.weightPercent,
        actions: [],
        atTopLevel: 0,
      };
      byDomain.set(domain.code, entry);
    }

    const targetIndex = nextLevelIndex(options.length, currentIndex);

    // Already at the top: counted so the plan can show progress, but given no action. A plan
    // that lists everything a school already does well buries the part that needs work.
    if (targetIndex === null) {
      atTopLevel += 1;
      entry.atTopLevel += 1;
      continue;
    }

    const target = options[targetIndex]!;
    entry.actions.push({
      parameterCode: param.code,
      parameterTitleEn: param.titleEn,
      parameterTitleHi: param.titleHi,
      currentLevel: options[currentIndex]!.order,
      targetLevel: target.order,
      targetDescriptionEn: target.labelEn,
      targetDescriptionHi: target.labelHi,
    });
  }

  const domains = [...byDomain.values()]
    .filter((d) => d.actions.length > 0)
    .map((d) => ({
      ...d,
      // Worst first: an indicator at level 1 is further from compliance than one at level 2,
      // and the code keeps the order stable where levels tie.
      actions: d.actions.sort(
        (a, b) => a.currentLevel - b.currentLevel || a.parameterCode.localeCompare(b.parameterCode),
      ),
    }))
    .sort(
      (a, b) =>
        // Heaviest domain first, because that is where a level gained moves the score most.
        // Domain weights are currently an equal 20% placeholder in the seed, so this ordering
        // will only start to mean something once SSSA supplies the real weights.
        (b.weightPercent ?? 0) - (a.weightPercent ?? 0) ||
        b.actions.length - a.actions.length ||
        a.code.localeCompare(b.code),
    );

  return {
    schoolUdise,
    cycleName: cycle.name,
    answered,
    atTopLevel,
    domains,
    notStarted: false,
  };
}
